### ISSUE TITLE
Delay when switching to Berlin tab in Slider Puzzle with qt backend.

### ISSUE THREAD

**Issue by lukas-jung** [slint-ui/slint#1214]
Delay when switching to Berlin tab in Slider Puzzle with qt backend:

Switching the tab takes a suspiciously long time. I think something odd might be happening there.
It works fine with the GL Backend.

**Comment by ogoffart** [comment]
The Image source is dirty so the cache is dirty, and it needs to decode the embedded jpeg for every `Image` (every tile).
Since this is not loading from a file name, the internal Qt cache doesn't kick in.
So it takes some time to do that and there is a small delay.

the GL backend is not impacted by that because it has a global Texture cache that use the pointer to the actual resource as a key.

**Comment by ogoffart** [comment]
The image cache was moved into core and doesn't suffer this problem.
