### ISSUE TITLE
Change `slint::Window::new` to take a `&Weak` instead of a `Weak`

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#1534]
In the API review and prototyping we found out that this makes the caller code easier to write and read, as `Rc::new_cyclic` already provides us with a weak.

**Comment by ogoffart** [comment]
Actually i'm a bit unsure if we should do that now.  In #1549  I tried the same for the renderer, and the code is actually more ugly.

Instead of 
```rust
window: Window::new(weak.clone()),  // currently
```
it will become
```rust
window: Window::new(&(weak.clone() as _)), // what happens if weak is a reference
```

Just 
```rust
window: Window::new(weak),
```
 
don't seam to work because it doesn' coerce.

Maybe it is possible to play with some generic or `&impl Into<Weak<dyn ...>>`   or something like that. But i'm not sure if this is better
