### ISSUE TITLE
Improve `TargetPixel` trait

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#1539]
In the API review we decided to change the `TargetPixel` API to have better names and make it possible to optimise the representation for colors for blending.

```rust
/// Trait for the pixels in the buffer
pub trait TargetPixel: Sized + Copy {
    type BlendableColor: From<Color> + Copy;
    /// Blend a single pixel with a color
    fn blend(&mut self, color: Self::BlendableColor);
    /// Blend a color for all the pixel in the slice.
    fn blend_slice(to_blend: &mut [Self], color: Self::BlendableColor);
    /// Create a pixel from the red, gree, blue component in the range 0..=255
    fn from_rgb(red: u8, green: u8, blue: u8) -> Self;
}
```

**Comment by ogoffart** [comment]
I had an attempt at adding the BlendableColor, but it turns out that this is fairly intrusive:
 - If we want to keep BlendableColor in the renderer command, then we  need to make all the internals of the software renderer generic (sometimes in not-so-obvious ways)
 - Also we need to do some operation on the color like interpolate it with another color for the border rectangle drawing. So we'd need to add more function to the BlendableColor trait.
 - If we want to maintain the BlendableColor in the inner structures, then we must also not be more than u32,  but the ideal representation for rgb565 i was thinking about would be bigger if we include apha.
 - the blend_slice could be implemented so that not to call blend for every pixel anyway.


So i think we probably should not do that now.

**Comment by tronical** [comment]
#1576 implements the conversion to and from `Rgb8Pixel`. Closing this as discussed :)
