### ISSUE TITLE
RFC: Component declaration

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#1682]
We want to change the component declaration so that
 - The declaration of globals, structs, and comonenent is more consitant
 - Not to require a base element  (use composition instead)

Following the discussion in https://github.com/slint-ui/slint/issues/191#issuecomment-938811947 we came up with

```slint
component Foo {
   property <int> yy : 42;
   rect := Rectangle { /* .. */ }
    //...
}

component Bar inherits Window {
   title: "foobar";
    //...
}

struct Stru {
  foo: int, bar: string
}

global Glob {
   property <int> yy: 42;
}
```

So:

-  introduce next component with the `component` contextual keyword.  (Question: is that the right word, should it be `element`?)
- Remove the `:=` in component or global declaration
- Make inheritance optional

**Comment by ogoffart** [comment]
Edited the description to keep inheritence

**Comment by jturcotte** [comment]
About 
```
component Foo {
   property <int> yy : 42;
   rect := Rectangle { /* .. */ }
    //...
}
```

Is this equivalent to inheriting from some item class with only [common properties](https://slint-ui.com/releases/0.3.0/docs/rust/slint/docs/builtin_elements/index.html#common-properties)?

I think you have eliding of trivial rectangles in the compiler, maybe it would be nice to partly document that behavior so that developers are not tempted to use inheritance to prune their item tree.

**Comment by ogoffart** [comment]
@jturcotte: Yes it is exactly that. And you're right we should document that properly.

**Comment by tronical** [comment]
I suppose that this can be ... closed? :)
