### ISSUE TITLE
Can't input Korean characters in Windows 11

### ISSUE THREAD

**Issue by teminian** [slint-ui/slint#1706]
**Slint version:** 0.3.0
**OS:** Windows 11, Skia (no OpenGL)
**Sypmtom:**
I can't input Korean characters in Windows, even though my keyboard layout is Korean and I can input Korean characters without issues in other applications. More exactly, the IME doesn't change from alphabet input mode to Korean input mode when I try to change the mode when Korean IME is in use(Korean IME provides two input modes, English and Korean), which I didn't experience this in 0.2.X.

The only way I can input Korean is copy-and-paste Korean text from other applications.

Thank you in advance for for your cooperation.

**Comment by tronical** [comment]
Indeed, input method support is currently limited to IME commit events, which is by far insufficient.

Odd that there was a difference in experience in 0.2.x, but this may have been due to a change in the underlying winit library. Either way we need to implement the correct IME event handling and hints. I'll prioritise that.

**Comment by tronical** [comment]
Hi @teminian - I've merged the initial input method support. Could you give it a try and see if you spot anything out of the ordinary with Korean?

**Comment by teminian** [comment]
I tested new `master` and it works! And even more, this master fixes two more issues, 
1. https://github.com/slint-ui/slint/issues/1138 , which was also reported by me
2. I can see koyboard cursor(or caret)

Here's the screenshot for you.
![image](https://user-images.githubusercontent.com/16410454/194676292-9960c0c6-3f6a-4e9e-9371-cd38a01bb2ab.png)

I think you can safely close and mark it as resolved.

**Comment by tronical** [comment]
Thanks for checking - much appreciated!!

I’ll close this after implementing the Qt side. The other issue with the hanging characters is indeed fixed by the Skia renderer. It’s still there with the femtovg one. Need to tackle this when adding text selection to the software Renderer and then use the same text layout code.
