### ISSUE TITLE
Consider joining states and transitions declarations

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#1850]
Currently states and transitions are declared separately:

```
states [
    foo when bar: {
        background: blue;
    }
    baz when fob: {
        background: green;
    }
]

transitions [
    out foo : {
        animate background { duration: 250ms; }
    }
]
```

It might make sense to allow combining both sections into one:

```
states [
    foo when bar: {
        background: blue;

        out {
            animate background { duration: 250ms; }
        }

        // shorthand:
        out animate background { ... }
    }
    baz when fob: {
        background: green;
    }
]
```

**Comment by ogoffart** [comment]
States declarations typically look like this:
```
property<bool> pressed;
states [
     pressed when pressed: {
         ...
```

The name was only used to refer to the state in the transition, but of we remove the transition scope by putting the animation directly in the state, then we don't need the name at all on slint.
It would only be used in the design tool, as a user visible string. 

Should we make the name optional? Or within quote since it is a human name?

Maybe there would be a reason to name states in slint if we want some imperative way to set state. (Or if we want to have a next state)

I wonder if we can come up with a better syntax to declare states

**Comment by tronical** [comment]
The name is indeed quite useful for tooling. Perhaps we can have a short-hand syntax? `pressed: { … }` is short for `pressed when pressed: { … }` and `toucharea.pressed: {…}` short-hand for `pressed when toucharea.pressed : { … }`.

**Comment by ogoffart** [comment]
The question is also where should states declaration be allowed.
Currently it's allowed in any part of the element tree,  but maybe we should consider restricting that to the component root. I'm just thinking it makes more sense of the whole component to be in a given state. Or how would the interface of the design tool work?

Also maybe we could have several states group for orthogonal states (that changes different properties)
