### ISSUE TITLE
public, private and readonly properties

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#191]
We want to be able to declare the properties as public, private, or protected.
Currently all top level properties are public.

The motivation is not only for performance (since knowing that a property cannot be accessed or written from the outside would allow to optimize things) but also for code hygiene.
For example, do we really want to allow changing property in states that could also be set from the outside.

### Updated suggestion:

We classify the property in the different category:

 - **`in`**: This is a property that can be set by the user of the component, but cannot be set with `=` by the component itself. (Most properties)
 - **`out`**: Properties that can only be set within the component. You cannot assign a binding from the outside. (eg: `pressed`)
 - **`in-out`**: property that can be set both from the inside and outside.
 - (nothing): private properties can can only be accessed from the component

Example of property declarations:

```slint
   in property <brush> background: blue; 
   out property <bool> pressed: touch-area.pressed;
   in-out property <int> value <=> slider.value;
   property <int> past_value: 32;  // this is private
```

We will also recommend inheriting from a "base" element that doesn't have any properties to it so that it would not be exposed.

Unresolved question:

 - [ ] Do we need to always have the `property` contextual keyword (`input property <foo> bar`)  or is just one enough (`input <foo> bar`)

<details>
  <summary>Original suggestion</summary>

* Requiring `public`/`private`/`readonly` annotation when defining properties
* Require a `public`/`private`/`readonly` annotation when defining components to specify the default access of inherited property
* Allow to change the visibility of inherited property with the `public foo;`/`private bar;`/`readonly buz;`

```
Button := private Rectangle {
 // None of Rectangle's properties can be used by users of Button
 readonly property<bool> pressed;
 private property<int> internal_state;
}

Button1 := public Rectangle {
    // All properties of Rectangle are readable/writable to users of Button
}

Button2 := readonly Rectangle {
    // All of Rectangle's properties become read-only to users of Button, but
    // Button2 itself can still assign bindings
    color: pressed ? blue : red;
}

Foo := private Button {
   // Should be allowed to override and create a new property  (but we can also make it forbidden for now)
   private property<string> internal_state: "Foo";
}

Button := private Rectangle {
   // We want the Rectangle's color to be public
   public color;
}

Button := public Rectangle {
    // Just hide the Rectangle's color
    private color;
    readonly border-color;
}
```

Questions:

 - Do we want to force the use of such a keyword, or should there be a default, and if there is a default, which one?
 - Properties that are not at the top level don't matter since they can only be private, so no keyword required. Maybe non top level property does make sense?
 - Syntax: Are these keyword the best we can come up?  Should we be able to elide the `property`  keyword:
```
   private <int> foo;
   public <string> bar;
   readonly <float> xxx;
```

</details>

**Comment by bwalter** [comment]
My 2 cents here: while it's definitely an improvement, the experience has shown that such "code hygiene" issues are better solved by avoiding inheritance in favor of composition. I'm wondering how it would be properly solved for 60fps but this is definitely one of the architectural issues which make QML projects hard to maintain.

**Comment by ogoffart** [comment]
@bwalter: In our implementation we are using composition, so this issue is merely about the syntax and, as you've identifier, hygiene to allow developers to define a good encapsulation for their components. In your opinion, what would be the alternative syntax?

**Comment by bwalter** [comment]
Fully agree with getting rid of the custom properties in inner elements. It's still time to simplify a lot which is a win-win for both maintainers and developers (+ easier documention ;)).

Another idea for huge simplification would be in my opinion to tackle issues like bi-directional bindings and (accidental) binding removal (e.g. when imperatively setting a bound property) which were for many Qt developers a big source of confusion and made QML development non-idiomatic...

**Comment by tronical** [comment]
Great feedback and suggestions! I love the consistency that it brings. I don’t mind the lack of inner properties. I like them because of the locality they help maintain when components become large, but that’s probably minor compared to the advantages you’re both outlining. Count me in :)

**Comment by glaebhoerl** [comment]
> (accidental) binding removal (e.g. when imperatively setting a bound property) 

I think it'd be great if there were a strict separation between (a) readonly properties, whose RHSes may be dynamic and which get reevaluated automatically, vs. (b) mutable properties, which can be manually overwritten in imperative code, but whose initializer RHS may only be a 'static value', i.e. it can't reference other properties, only literals. Readonly properties could still reference mutable ones as usual, so I don't think this loses much expressiveness, you just have to be up-front about what the purpose of a given property is.

**Comment by ogoffart** [comment]
We discussed that again and will finally tackle change in the language soon.
I split the component declaration in another issue:  https://github.com/slint-ui/slint/issues/1682
I updated the description to mention the new keyword we discueesed: `input`  `output` and `inout`

**Comment by ogoffart** [comment]
There is now an implementation of this in master behind the `SLINT_EXPERIMENTAL_SYNTAX` feature gate.


After implementing this, it turns out that `inout` and `input` are two keywords that looks really similar to eachother and are easy to confuse.  We might want to rename `inout` to something else.

**Comment by glaebhoerl** [comment]
I like the new access control keywords, that was indeed another source of ambiguity and bugs on the QML codebase I worked on (we adopted `ext_foo` as a naming convention for input properties as a mitigation).

As a somewhat orthogonal matter to access control, you're not as concerned apparently about property bindings getting inadvertently broken by mutation?

**Comment by ogoffart** [comment]
> As a somewhat orthogonal matter to access control, you're not as concerned apparently about property bindings getting inadvertently broken by mutation?

I hope this will fix most cases, since one cannot set input property from within the component, and one cannot set binding to output property outside of the component.

Could you give an example of problematic code?  Do you have a suggestion on how to fix it?

**Comment by ogoffart** [comment]
> it turns out that `inout` and `input` are two keywords that looks really similar to eachother and are easy to confuse. 

Maybe we could write that `input output property<...> foo` with two words

**Comment by tronical** [comment]
That seems like a reasonable compromise to me.

**Comment by glaebhoerl** [comment]
> Could you give an example of problematic code? Do you have a suggestion on how to fix it?

The code base (in addition to non-public) was big and gnarly (QML files with four-digit LOC), which is both why it's hard to give a neatly encapsulated example, and why better support from the language would've been valuable.

It's more of a code evolution and clarity-of-intent thing, though I guess the same could be said about the input/output qualifiers.

Typical scenario: a developer has been assigned the task of fixing some small bug, or maybe extending a feature. Perhaps they're recently hired, or just new to the codebase. They dive into the code, and discover that a property `numValidUsers` declared on line 119:

```qml
property int numValidUsers: /*complicated expression*/
```
has the "wrong" value, for their purposes, on line 847. If they're conscientious, alert, and aware of the pitfalls, they now need to determine: does the RHS value change over time, and does anywhere else in the code depend on it doing so? Or is it safe to simply overwrite the value? To answer this, they need to Ctrl-F in the rest of the code for the property and/or constituents of its RHS. If they're tired or unaware, maybe they just put the overwrite in, mark the bug as resolved, and get on with their day; now the code reviewer will face the same question. (You can imagine further twists here: maybe the assignment is just one line of a large diff; maybe adding it was okay at that point, but later another developer assumes the property does *not* get overwritten (without thinking to check), and starts using it in a 'reactive' way, which ends up... working fine... most of the time.)

The input/output controls do ameliorate this to *some* extent, but don't really make it go away. For private and `inout` properties, it's the same as ever. For `input` properties... is the default initializer also a binding that can be broken by mutation? (I think this is actually *two* questions: in the component defining it, and where the component is instantiated.)

My preferred solution is the one I suggested earlier: make a sharp distinction between properties that get their value from mutation, and ones that get it by re-evaluating their RHS. When the developer finds the property on line 119, they should see the intent right away, without requiring Ctrl-F. Is there an actual *use case* for properties whose values update together with their RHS, right up until the *first time* they get mutated? It feels more like an accidental "feature", to me.

Devil's in the details though, with respect to combining this with the input/output controls.

**Comment by ogoffart** [comment]
@glaebhoerl  So you would like to have an extra qualified for "assignable" or something like that? or maybe that would be a more an annotation on the binding.

```
Rectangle { 
   final background: blue; // can't be assigned anywhere else
   final property <length> xxx: 42px + parent.x;    // same
}
```

Or would you prefer if there was an `assignable` label, or `replaceable` that mean the opposite? 

I wonder if that is not a bit too much.

**Comment by bjorn** [comment]
> After implementing this, it turns out that `inout` and `input` are two keywords that looks really similar to eachother and are easy to confuse. We might want to rename `inout` to something else.

Did you consider renaming the other two instead, so you have `in`, `out` and `inout` / `in out`? I think "input" and "output" are already rather verbose, and from C# many people are already used to simply [`in`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/in-parameter-modifier) and [`out`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/out-parameter-modifier) on function parameters with similar meaning.

**Comment by jturcotte** [comment]
```
  input output property<string> text;
  property<int> internal-state; //Private by default
```

Just my feeling, but I think that for learning the language and quick prototyping, having to remember and type `input output` everywhere is tedious. For performance and maintenance it's bad, but for new users and development I think that `input output` is a better default.

Also I find that calling `internal-state` a property a bit misleading, but since there are no local variable in bindings this is what users need to use for any intermediate state. So overall, as a random user with only a part of the picture, I'd favor `property<string> text;` defaulting to input output (thus the long term could be removed from the spec), and I'd rename private properties to something like `variable<int> internal-state`.

**Comment by ogoffart** [comment]
@bjorn you're right. `in`, `out`, and `inout` might be better.   In general we try to avoid abbreviation because readability is more important than verbosity. But it is true that these are already used keywords. I'll think about it.

@jturcotte  This is not about performance (we actually already auto-detect things that aren't change in most cases), but this is about self-documenting code and correctness by avoiding mistake. And also being explicit about what properties should be shown for editing in a design tool. I think the most common properties are not `input output` but most properties in my experience are just `input`.  But the default is very important for correctness, that's why it should be private.  But you have a point saying that it is not really a property.

**Comment by glaebhoerl** [comment]
>  So you would like to have an extra qualified for "assignable" or something like that?

That would be the simplest version, but probably not the best one. There are a few separate issues.

First, just sticking `readonly` or a similar keyword on non-mutable properties like QML does (or vice versa) is fine for that half of it (and better than nothing), but still leaves the original problem present for non-readonly properties (otherwise there'd be no problem in QML either). You can still make a non-readonly property with a dynamically changing RHS that gets reevaluated automatically at some points in the code, and then gets randomly broken by an assignment at some other point. A true solution would mean that there'd be one kind of property that can be automatically re-evaluated but not assigned, and another that can be assigned but not re-evaluated. One option is to simply not re-evaluate the RHS of mutable properties. If that's considered potentially confusing, another option is to only allow inherently-non-changing expressions (e.g. literals) in the RHS of mutable properties, and for other cases, have a separate initializer or constructor block somewhere in the component that can assign initial values to mutable properties (like QML's `Component.onCompleted`, I don't know if Slint already has an equivalent).

In terms of the auto-update propagation graph, the root nodes would be mutable properties, the interior and leaf nodes readonly properties, and there'd be no conflation between the two.

The other design question is how to factor the qualifiers (and their concrete syntax). Mutable vs. readonly and public vs. private are two orthogonal axes that can be combined either way, so those four cases would be easy enough (just need to decide on keywords) on their own. But input and output properties are more "interesting". For input properties, ideally it'd be the *client* (instantiator) of the component that'd decide whether they want the property to be readonly (initialized with some auto-updating expression) or mutable (updated manually). The component originally declaring the property doesn't care either way; all that matters from their perspective is that *they* can't overwrite it. Meanwhile, for output properties, the situation is basically symmetric: the outside world doesn't care whether it's internally implemented using a single auto-updating expression, or with multiple mutable assignments.

But an output property that's internally implemented as a readonly property is just the same thing as a public readonly property. So really there'd be the expected six cases at the point of declaration: public mutable, private mutable, public readonly, private readonly, output (readonly on the outside, mutable on the inside), and input (mutable on the outside, readonly on the inside), with the latter having a further mutable vs. readonly choice at the point of instantiation.

The best way to provide syntax for these isn't obvious though. Simply use the same adjectives from above as keywords? Perhaps split `property` itself in two (maybe the mutable one could be `variable` instead)? I can think about this some more if you find the motivation the least bit compelling, but if it'd be wasted work (you didn't sound enthusiastic...), I'll just let it drop.

**Comment by ogoffart** [comment]
We're going with `in`, `out` and `in-out`  in https://github.com/slint-ui/slint/pull/1824

**Comment by ogoffart** [comment]
The 0.3.2 already has the new keywords

**Comment by nmpribeiro** [comment]
Docs and examples do not reflect this (for instance the [tile game](https://slint-ui.com/releases/0.3.5/docs/tutorial/rust/polishing_the_tile.html))

**Comment by tronical** [comment]
In the next release it will: https://slint-ui.com/snapshots/master/docs/tutorial/rust/polishing_the_tile.html :-)
