### ISSUE TITLE
WASM input doesn't work on mobile

### ISSUE THREAD

**Issue by jgarvin** [slint-ui/slint#215]
With the exception of iced, every rust gui WASM framework I've tried has the issue that the browser doesn't know when you have clicked inside an input field, so the mobile keyboard never pops up. On desktops this also causes issues with the Vimium plugin and probably others, because they capture keyboard input unless they think that you have clicked inside an input field. You can see the issue in any of the demos for example this one: https://sixtyfps.io/demos/todo/

**Comment by tronical** [comment]
You're right, there are a few fundamental issues with regards to text input with this, more specifically with HTML Canvas based rendering. egui has a pretty well working hack around this particular issue of input on mobile by placing a HTML input element underneath the rendering canvas and forcing focus on it, in order to bring up the virtual keyboard.

**Comment by ogoffart** [comment]
This is implemented now.
