### ISSUE TITLE
The property font-size in Button does not work

### ISSUE THREAD

**Issue by Zhou-Pixel** [slint-ui/slint#2194]
code:
# //hello.slint

```js
import { Button } from "std-widgets.slint";
export component Example inherits Window {
    preferred-width: 800px;
    preferred-height: 480px;
    GridLayout {  
        Button {
            property <int> counter: 3;
            clicked => { self.counter += 3 }
            text: "testtest";
            font-size: 100px;//does not work
        }
        Text {  
            text: "hello";
            font-size: 80px;//works
        }
    }

}

# //main.rs

```
# //main.rs
```rust
slint::include_modules!();
fn main() {
    Example::new().run();
}
```

# Application:
![image](https://user-images.githubusercontent.com/72525794/217185099-f5d0f483-8dcf-481f-88db-f384b7433dad.png)

env: linux, x11, kernel6.1.9

Both Qt5.15.8 and winit have the same problem

**Comment by ogoffart** [comment]
Thanks for reporting an issue.

This property was an internal property at some point but it was not documented and was exported by mistake.
It will not be present in future version.

There have been some request before to be able to customize a bit widgets such as background color, or, in this case, the font-size. (eg: #1232)
But our customization here is lacking: either the widgets looks exactly like the style, or you have to write a custom button yourself as a component that can have a different look.

May I ask what's the use case to increase the font of a button? Is it because you would like every button to have bigger fonts? Or is it just to emphasis a single Button?

**Comment by Zhou-Pixel** [comment]
> 

The default font size is too small for me and I think a bigger font would make it clearer for the user

**Comment by Zhou-Pixel** [comment]
> Perhaps you could change the default font size for all text elements using the `default-font-size` property on the `Window` element?

It seems setting default-font-size for the window will affect other controls and I think it is necessary to set the font of each control individually as a gui framework, such as Qt

**Comment by ogoffart** [comment]
>  I think it is necessary to set the font of each control individually as a gui framework, such as Qt

I agree that we should have our standard widget more themable.
But the thing is that they are meant to be native, and you can't always change the appearence of native widgets.
Right now, if you want customizable widgets, you can re-implement the widgets as custom widgets. https://docs.rs/slint/latest/slint/docs/recipes/index.html#custom-widgets

**Comment by ogoffart** [comment]
The Button no longer expose this property in any style.
