### ISSUE TITLE
Add `debug` property to all elements to ease debugging

### ISSUE THREAD

**Issue by matklad** [slint-ui/slint#239]
`debug` should draw some kind of a border around the element. Right now, I am trying to add rectangles to that effect, but they affect layout :(

![image](https://user-images.githubusercontent.com/1711539/119195059-ad437880-ba8c-11eb-86d4-390d4db26b1f.png)

Alternatively, add some global property which displays all borders?

**Comment by ogoffart** [comment]
So something like  `debug: blue;`  would be syntactic sugar to  
`Rectangle { width: 100%; height: 100%;  border-color: blue; border-width: 2px;   }` ?

**Comment by matklad** [comment]
I think it would be better if it was a first-class thing. Debug `true` is a property, which is just available on every element. During rendering, we note which elements have this property, and render additional info.

For invisible elements like layouts, that info would be borders (and maybe padding). 

But for something like Text that could be borders + baseline.

**Comment by flukejones** [comment]
I found myself doing a similar thing with bordered transparent rectangles to work out exactly where the alignment/size/etc is.

On the same note having something to draw the text baselines, and object centers (as a cross perhaps) would also be very helpful.

**Comment by jrmoulton** [comment]
For this implementation only the exported elements would need to have the property correct? Or would it be better to have it on _all_ elements?

**Comment by ogoffart** [comment]
The idea would be to have it in all elements.

The way yo implement it would be to do a pass similar to the clip pass.
the clip pass (in `passes/clip.rs`) add a Clip element if a `clip`  property is defined. but instead of adding a Clip, you would want to add a Ractangle of a given color.

So in order to implement that you'd need:
 - add "debug" in the list of properties which are always defined (in RESERVED_OTHER_PROPERTIES)
 - copy the clip pass and make a debug pass, but instead of generating a "Clip" element, generate a "Rectangle" element.  Also you might not need to change the hierarchy of children
 - document and test the property.
 
Now that i think of it, we might also need a hack so that the property can be set, but never accessed. So that  `debug(123);`  continue to print the thing and not access the debug property.  That needs to be hacked in lookup.rs, i think.

**Comment by jrmoulton** [comment]
Ahh ok. I'll start working on this issue. Thanks!

**Comment by jturcotte** [comment]
One thing I thought would be nice is if the whole LSP preview would enter "debug mode" when the `Alt` key is kept held, or something like that.

Being able to hover elements with the mouse while in that debug state and have a tooltip that shows its numerical metrics would also be nice, but it would probably be sometimes difficult to hover non-leaf element if they are completely covered by children. So maybe the metrics would better eventually go into a tree-list of element for a scene. But maybe I'm thinking too far ahead.

**Comment by ogoffart** [comment]
Not sure the LSP has a way to intercept Alt.  But maybe we could use "documentHightlight" https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentHighlight or something like that.

**Comment by jturcotte** [comment]
I meant when the focus is on the preview window, which it would need to if hoover would also be handled. But anything going through the protocol would also be nice.
Something related to the editor cursor position could be extra magic, but for elements created in a for loop this could be messy.

**Comment by jturcotte** [comment]
I guess this wouldn't work if the preview is running on a separate device that doesn't have keyboard. In that case I guess that just adding `debug: true` in the code to highlight the part the developer is curious about will work better overall for now.

If anything, doing this through LSP or any extended remote debugging interface, if you have one in the future, would be a better idea than relying on the keyboard on the preview window.

**Comment by ogoffart** [comment]
I'd say this is not needed anymore since the LSP now highlights the selected Element in the preview
