### ISSUE TITLE
Panic when creating empty window with layout

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#2413]
The following test-case produces a panic in the live-preview or when run with Slint-viewer:

```
export component App {
    VerticalLayout {
    }
}
```

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other("Attempting to create an OpenGL window surface with an invalid width: 0")', tools/viewer/main.rs:96:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

With the Qt backend there's no panic, but also no window is shown at all (on macOS).

**Comment by ogoffart** [comment]
This was my feeling that we should some how handle this case.  Perhaps giving a minimum size of 1x1  ?

**Comment by tronical** [comment]
I agree.

It doesn't make sense to me to communicate a size 0x0 or a minimum-size of 0x0 to a window manager on macOS, Linux, or Windows. Do you agree, or do you think it's better to have an "invisible" window and just not panic?

**Comment by ogoffart** [comment]
This is not only about the preview, but also about the real application

Options:
 - Always make a window bigger than some threshold (1x1)
 - Not return an error have an invisible window
 - return an a specific error, and handle it in the viewer and in the preview instead of panicking (eg, show a "compile" error instead)


Always make sure the window is bigger than some threshold seems easier (in the backend)

**Comment by tronical** [comment]
> This is not only about the preview, but also about the real application

Yes, exactly. A 0x0 size on a window that is supposed to be shown doesn't make sense to me for applications.

> Always make sure the window is bigger than some threshold seems easier (in the backend)

That is also my preference.
