### ISSUE TITLE
Extend image api for JavaScript/TypeScript

### ISSUE THREAD

**Issue by FloVanGH** [slint-ui/slint#2474]
At the moment it's possible to generate an image object by setting a local path:

```typescript
myWindow.image = "/path/to/my/foo/image.png";
```
What this api does not provide is a way to generate an image from an array buffer like https://docs.rs/slint/1.0.0/slint/struct.Image.html#method.from_rgba8. But this could be very helpful if you want to use a third party library to render stuff like: https://www.npmjs.com/package/three-software-renderer.

A suggestion how a new api could looks like:

```typescript
// load an image from an data array, with width and height
// ImageData is inspired  by https://developer.mozilla.org/en-US/docs/Web/API/ImageData/ImageData
myWindow.image = Image.fromImageData(new ImageData(data, 100, 100));

// load an local image
myWindow.image = new Image("/path/to/my/foo/image.png");

// load an image from trough http
myWindow.image = new Image("https://way/to/../image.png");
```

This would be a breaking change if this would replaced:

```typescript
myWindow.image = "/path/to/my/foo/image.png";
```

**Comment by tronical** [comment]
So the basic idea is to accept an object that has the same _shape_ as [`ImageData`](https://developer.mozilla.org/en-US/docs/Web/API/ImageData) and interpret the Uint8ClampedArray inside as RGBA pixel data.

We can either accept that for properties of type Image - so let the setter dynamically see if the provided value is a string or an object, and if the latter, then assume that shape. And in TypeScript terms that would take a union.

Alternatively, we could make `Image` an explicit type in our API that has a constructor accepting a string or an `ImageData` type (for which we should define the interface, like we do for model).

I'm very much in favor of introducing an `Image` type instead of letting `myWindow.image` accept either a string or `ImageData`, because the former allows to also later retrieve the width/height, while the latter is a one-way ticket.

I don't see why this has to be a breaking change though. What am I missing? :)

**Comment by FloVanGH** [comment]
> I'm very much in favor of introducing an Image type instead of letting myWindow.image accept either a string or ImageData, because the former allows to also later retrieve the width/height, while the latter is a one-way ticket.

Me too.

> I don't see why this has to be a breaking change though. What am I missing? :)

If we only accept: 

```typescript
my_window.iamge = new Image(...);
```

then this will no longer work: 

```typescript
my_window.image = "/my/path/file.png";
```

**Comment by tronical** [comment]
Ah yes, that's true. I favor avoiding that.

**Comment by FloVanGH** [comment]
> Ah yes, that's true. I favor avoiding that.

Ok then both ways. 

My suggestion:

```typescript
my_window.image = "/path/to/my/image.png";
my_window.image = new Image("/path/to/my/image.png");
my_window.image = new Image(new ImageData(data, 10, 10));
```

**Comment by tronical** [comment]
Is there any work left for this issue?

**Comment by FloVanGH** [comment]
no. thanks fore the reminder ;-)
