### ISSUE TITLE
use of undeclared type `MainWindow`

### ISSUE THREAD

**Issue by kN4im3** [slint-ui/slint#2499]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/28520738/230318006-f03e4000-5374-43f2-a0e7-d88941ce93a3.png">
<img width="808" alt="image" src="https://user-images.githubusercontent.com/28520738/230318155-a379b48a-9f56-4911-98b0-f72a0193ea54.png">

**Comment by kN4im3** [comment]
This problem seems to be an error caused by Image

**Comment by ogoffart** [comment]
Right, you should have had an error exaplaining that the image cannot be loaded.

Then because of that error, the macro didn't generate any code and you get more errors.
It would be nice if we could actually still generate minimal code that contains the structs in some way that this error doesn't show
