### ISSUE TITLE
Re-used components in the repeater with stale state

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#2598]
Step to reproduce with the todo example:
1. open the todo example, ie https://slint-ui.com/demos/todo/
2. Check "Test the application"
3. check "Hide Done Items"  (not remove)
4. Observe that "profit" is checked.

What happens is that the "hide done items" will replace the model with another model (the FilterModel)
This should normally reset all items.

But since  https://github.com/slint-ui/slint/pull/1954  we re-use the items, and the checkbox was manually checked, breaking existing bindings. So we re-use a component that has a broken binding.

Discussion in https://chat.slint-ui.com/public/pl/m6mwp1f3q3d3by6rp81zw3utqy

We need to either re-create each component (revert #1954). Or perhaps we can get away by calling init again, this would probably fix that particular issue since it would re-create bindings and reset non-defaulted property. But there are still some state that wouldn't be reset.

**Comment by ogoffart** [comment]
This was repoorted in #3711 again.  This is IMHO quite a bad bug and should be fixed.
@tronical any objection reveting #1954 ?

**Comment by tronical** [comment]
I agree that's a bad bug. I guess we have to revert it. The primary motivation for the re-use was to avoid that init() is called a number of times that doesn't make sense:

```
export Demo := Window {
    height: 300px;
    width: 300px;
    property <int> creation-count: 0;
    property <bool> open: false;
    
    VerticalLayout {
        Text {
            text: creation-count;
        }
        if open: Rectangle {
            background: green;
            init => { creation-count += 1; }
        }
    }

    TouchArea {
        clicked => {
            open = !open;
        }
    }
}
```

If you click once, init is called twice. I find it hard to explain that behavior, but perhaps the fix for that is something else?

**Comment by qarmin** [comment]
Not sure if this is the same bug, because happens without replacing model, but this cause that it is almost impossible to use listview since it breaks in random moments and I don't know how to prevent this situations  - [slintpad example](https://slint.dev/releases/1.2.2/editor/?snippet=import+%7B+Button%2C+VerticalBox+%2C+HorizontalBox%2C+TabWidget%2C+ListView%2C+StandardListView%2C+StandardTableView%2C+CheckBox%7D+from+%22std-widgets.slint%22%3B%0A%0A%0A%0Aexport+component+SelectableTableView+inherits+Rectangle+%7B%0A++++in+property+%3C%5Bstring%5D%3E+columns%3B%0A++++in-out+property+%3C%5B%7Bchecked%3A+bool%2C+header_row%3A+bool%2C+selected_row%3A+bool%2C+val%3A%5Bstring%5D%7D%5D%3E+values%3B%0A%0A++++private+property+%3C%5Blength%5D%3E+column_sizes%3A+%5B30px%2C+100px%2C+100px%2C+100px%5D%3B%0A++++private+property+%3Cint%3E+column_number%3A+4%3B%0A%0A++++in-out+property+%3Cint%3E+selected_item%3A+-1%3B%0A%0A++++VerticalBox+%7B%0A++++++++padding%3A+5px%3B%0A++++++++%2F%2F+Widgets%0A++++++++HorizontalLayout+%7B%0A++++++++++++padding%3A+5px%3B+%0A++++++++++++spacing%3A+5px%3B%0A++++++++++++vertical-stretch%3A+0%3B%0A++++++++++++for+title%5Bidx%5D+in+root.columns+%3A+HorizontalLayout+%7B%0A++++++++++++++++width%3A+root.column_sizes%5Bidx%5D%3B%0A++++++++++++++++Text+%7B+overflow%3A+elide%3B+text%3A+title%3B+%7D%0A++++++++++++++++Rectangle+%7B%0A++++++++++++++++++++width%3A+1px%3B%0A++++++++++++++++++++background%3A+gray%3B%0A%0A++++++++++++++++++++TouchArea+%7B%0A++++++++++++++++++++++++width%3A+5px%3B%0A++++++++++++++++++++++++x%3A+%28parent.width+-+self.width%29+%2F+2%3B%0A++++++++++++++++++++++++property+%3Clength%3E+cached%3B%0A++++++++++++++++++++++++pointer-event%28event%29+%3D%3E+%7B%0A++++++++++++++++++++++++++++if+%28event.button+%3D%3D+PointerEventButton.left+%26%26+event.kind+%3D%3D+PointerEventKind.down%29+%7B%0A++++++++++++++++++++++++++++++++self.cached+%3D+root.column_sizes%5Bidx%5D%3B%0A++++++++++++++++++++++++++++%7D%0A++++++++++++++++++++++++%7D%0A++++++++++++++++++++++++moved+%3D%3E+%7B%0A++++++++++++++++++++++++++++if+%28self.pressed%29+%7B%0A++++++++++++++++++++++++++++++++root.column_sizes%5Bidx%5D+%2B%3D+%28self.mouse-x+-+self.pressed-x%29%3B%0A++++++++++++++++++++++++++++++++if+%28root.column_sizes%5Bidx%5D+%3C+20px%29+%7B%0A++++++++++++++++++++++++++++++++++++root.column_sizes%5Bidx%5D+%3D+20px%3B%0A++++++++++++++++++++++++++++++++%7D%0A++++++++++++++++++++++++++++%7D%0A++++++++++++++++++++++++%7D%0A++++++++++++++++++++++++mouse-cursor%3A+ew-resize%3B%0A++++++++++++++++++++%7D%0A++++++++++++++++%7D%0A++++++++++++%7D%0A++++++++%7D%0A++++++++list_view+%3A%3D+ListView+%7B%0A++++++++++++min-width%3A+100px%3B%0A++++++++++++for+r%5Bidx%5D+in+root.values+%3A+Rectangle+%7B%0A++++++++++++++++height%3A+30px%3B%0A++++++++++++++++background%3A+r.header-row+%3F+%23888888+%3A+%28touch-area.has-hover+%3F+%28r.selected_row+%3F+%23cccccc+%3A+%23dddddd%29+%3A+%28r.selected_row+%3F+%23cccccc%3A+%23dddddd%29%29%3B%0A++++++++++++++++%2F%2F+background%3A+touch-area.has-hover+%3F+%28selected+%3F+%23333333+%3A+%23222222%29+%3A+%28selected+%3F+%23333333%3A+%23222222%29%3B%0A%0A++++++++++++++++touch_area%3A%3D+TouchArea+%7B%0A++++++++++++++++++++clicked+%3D%3E+%7B%0A++++++++++++++++++++++++if+%28%21r.header_row%29+%7B%0A++++++++++++++++++++++++++++r.selected_row+%3D+%21r.selected_row%3B%0A++++++++++++++++++++++++++++if+%28root.selected-item+%3D%3D+-1%29+%7B%0A++++++++++++++++++++++++++++++++root.selected-item+%3D+idx%3B%0A++++++++++++++++++++++++++++%7D+else+%7B%0A++++++++++++++++++++++++++++++++if+%28r.selected_row+%3D%3D+true%29+%7B%0A++++++++++++++++++++++++++++++++++++root.values%5Broot.selected-item%5D.selected_row+%3D+false%3B%0A++++++++++++++++++++++++++++++++++++root.selected-item+%3D+idx%3B%0A++++++++++++++++++++++++++++++++%7D+else+%7B%0A++++++++++++++++++++++++++++++++++++root.selected-item+%3D+-1%3B%0A++++++++++++++++++++++++++++++++%7D%0A++++++++++++++++++++++++++++%7D%0A++++++++++++++++++++++++%7D%0A++++++++++++++++++++%7D%0A++++++++++++++++%7D%0A%0A++++++++++++++++HorizontalLayout+%7B%0A++++++++++++++++++++padding%3A+5px%3B%0A++++++++++++++++++++spacing%3A+5px%3B%0A++++++++++++++++++++%2F%2Fwidth%3A+root.column_sizes%5Bidx%5D%3B%0A%0A++++++++++++++++++++CheckBox+%7B%0A++++++++++++++++++++++++%2F%2Fmin-width%3A+200px%3B%0A++++++++++++++++++++++++visible%3A+%21r.header-row%3B%0A++++++++++++++++++++++++checked%3A+r.checked+%26%26+%21r.header-row%3B%0A++++++++++++++++++++++++width%3A+root.column-sizes%5B0%5D%3B%0A++++++++++++++++++++++++toggled+%3D%3E+%7B%0A++++++++++++++++++++++++++++r.checked+%3D+self.checked%3B%0A++++++++++++++++++++++++%7D%0A++++++++++++++++++++++++%2F%2F+preferred-width%3A+root.column-sizes%5B0%5D%3B%0A++++++++++++++++++++%7D%0A%0A++++++++++++++++++++HorizontalLayout+%7B%0A++++++++++++++++++++++++spacing%3A+5px%3B%0A++++++++++++++++++++++++for+f%5Bidx%5D+in+r.val+%3A+Text+%7B%0A++++++++++++++++++++++++++++width%3A+root.column-sizes%5Bidx+%2B+1%5D%3B%0A++++++++++++++++++++++++++++text%3A+f%3B%0A++++++++++++++++++++++++++++font-size%3A+12px%3B%0A%0A++++++++++++++++++++++++++++vertical-alignment%3A+center%3B%0A%0A++++++++++++++++++++++++++++overflow%3A+elide%3B%0A++++++++++++++++++++++++%7D%0A++++++++++++++++++++%7D%0A++++++++++++++++%7D%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A%0Aexport+component+MainWindow+inherits+Window+%7B%0A++++in-out+property+%3C%5B%7Bchecked%3A+bool%2C+header_row%3A+bool%2C+selected_row%3A+bool%2C+val%3A%5Bstring%5D%7D%5D%3E+empty_folder_model%3A+%5B%0A++++++++%7Bchecked%3A+false%2C+selected_row%3A+false%2C+header_row%3A+true%2C+val%3A+%5B%22kropkarz%22%2C+%22%2FXd1%22%2C+%2224.10.2023%22%5D%7D+%2C%0A++++++++%7Bchecked%3A+false%2C+selected_row%3A+false%2C+header_row%3A+false%2C+val%3A+%5B%22witasphere%22%2C+%22%2FXd1%2FImagerren2%22%2C+%2225.11.1991%22%5D%7D+%2C%0A++++++++%7Bchecked%3A+false%2C+selected_row%3A+false%2C+header_row%3A+false%2C+val%3A+%5B%22witasphere%22%2C+%22%2FXd1%2FImagerren2%22%2C+%2225.11.1991%22%5D%7D+%2C%0A++++++++%7Bchecked%3A+false%2C+selected_row%3A+false%2C+header_row%3A+false%2C+val%3A+%5B%22witasphere%22%2C+%22%2FXd1%2FImagerren2%22%2C+%2225.11.1991%22%5D%7D+%2C%0A++++++++%7Bchecked%3A+false%2C+selected_row%3A+false%2C+header_row%3A+false%2C+val%3A+%5B%22witasphere%22%2C+%22%2FXd1%2FImagerren2%22%2C+%2225.11.1991%22%5D%7D+%2C%0A++++++++%7Bchecked%3A+false%2C+selected_row%3A+false%2C+header_row%3A+false%2C+val%3A+%5B%22witasphere%22%2C+%22%2FXd1%2FImagerren2%22%2C+%2225.11.1991%22%5D%7D+%2C%0A++++++++%7Bchecked%3A+false%2C+selected_row%3A+false%2C+header_row%3A+false%2C+val%3A+%5B%22witasphere%22%2C+%22%2FXd1%2FImagerren2%22%2C+%2225.11.1991%22%5D%7D+%2C%0A++++++++%7Bchecked%3A+false%2C+selected_row%3A+false%2C+header_row%3A+false%2C+val%3A+%5B%22witasphere%22%2C+%22%2FXd1%2FImagerren2%22%2C+%2225.11.1991%22%5D%7D+%2C%0A++++++++%7Bchecked%3A+false%2C+selected_row%3A+false%2C+header_row%3A+false%2C+val%3A+%5B%22witasphere%22%2C+%22%2FXd1%2FImagerren2%22%2C+%2225.11.1991%22%5D%7D+%2C%0A++++++++%7Bchecked%3A+false%2C+selected_row%3A+false%2C+header_row%3A+false%2C+val%3A+%5B%22witasphere%22%2C+%22%2FXd1%2FImagerren2%22%2C+%2225.11.1991%22%5D%7D+%2C%0A++++++++%7Bchecked%3A+true%2C+selected_row%3A+false%2C+header_row%3A+false%2C+val%3A+%5B%22lokkaler%22%2C+%22%2FXd1%2FVide2%22%2C+%2201.23.1911%22%5D%7D%0A++++%5D%3B%0A++++%0A++++min-width%3A+200px%3B%0A++++VerticalBox+%7B%0A++++++++HorizontalBox+%7B%0A++++++++++++%2F%2F+min-width%3A+600px%3B%0A++++++++++++preferred-height%3A+300px%3B%0A+%0A++++++++++++SelectableTableView+%7B%0A++++++++++++++++min-width%3A+200px%3B%0A%0A++++++++++++++++columns%3A+%5B%22Selection%22%2C+%22Folder+Name%22%2C+%22Path%22%2C+%22Modification+Date%22%5D%3B%0A++++++++++++++++values+%3C%3D%3E+empty-folder-model%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D)

Simple selection logic(looks that logic works fine):
- if item is selected and clicked, deselect it
- if item is not selected and clicked, select it and deselect previously selected

https://github.com/slint-ui/slint/assets/41945903/0ec3e706-bde7-4962-a27a-159492ac8ac9

This works fine at start, but begin to select invalid rows, when I scroll even a little list.
After deselecting all elements and going to top, everything starts to work again
