### ISSUE TITLE
Documentation issue: Getting Started page not up to date with 1.0.2

### ISSUE THREAD

**Issue by abwitek** [slint-ui/slint#2689]
Again a minor one:

- Linux
- slint C++ API
- cmake, FetchContent with GIT_TAG release/1
- rustc 1.69.0 (84c898d65 2023-04-16)
- gcc 11.3.0, with c++17 standard

My file _my_application_ui.slint_ is copy/pasted from slint doc's (Getting Started page)[https://slint-ui.com/releases/1.0.2/docs/cpp/getting_started.html, version 1.0.2.

Generated setter for `my_label` property is marked deleted, which prevents the example code to compile as-is.

```
$ slint-compiler --version
slint-compiler 1.0.2
$ slint-compiler  my_application_ui.slint.slint | grep my_label
    inline auto get_my_label () const = delete /* the property 'my-label' is declared as private. Declare it as 'in', 'out', or 'in-out' to make it public */;
    inline auto set_my_label (const auto &) const = delete /* property 'my-label' is declared as private. Declare it as 'in' or 'in-out' to make it public */;
```

**Comment by ogoffart** [comment]
Thanks for the bug report! It is not so easy to spot mistake in documentation if  the snippets aren't tested.

The fix is to declare the property with `in`,  as in `in property my_label <=> label.text;`

Fixing in https://github.com/slint-ui/slint/pull/2691

The Slint snippets in the documentation are tested, but the C++ snippets are not :-/
