### ISSUE TITLE
Use tao instead of winit

### ISSUE THREAD

**Issue by wspl** [slint-ui/slint#2694]
In one of my recent projects, I tried replacing winit with [tao](https://github.com/tauri-apps/tao) in the winit-backend. Most features work well, and my program also gained many additional features, such as tray icons and resizable frameless windows.

Although Tao is based on an older winit fork and is not yet mature in features like IME, it offers a richer set of common functionalities, making it a potentially good alternative to winit. I think I will continue to research how to make tao work better with slint. Not just for my own projects, but also to bring it to the community.

I believe I'm not the first one to think of doing this, so I opened this issue in hopes of discussing it with maintainers and community members.

**Comment by tronical** [comment]
I think at the very least it's in our interest that Slint's APIs make it possible to write apps that use tao instead of winit: this requires (a) enough public platform APIs to forest events from Tao to Slint and forward windowing system requests from Slint to tao, and (b) public API for the renderers.

@FloVanGH did something like that with redox os, where he implemented the event loop on top of Slint and uses the software renderer.

So something similar should be possible today, but it comes with some caveats.

It's in our interest to stabilize the renderer APIs, add more features to the software renderer (like Florian is working on right now), and further extend the platform APIs.

I wonder if it would make sense perhaps to convert this issue into a discussion and then create spin-off issues for concrete items. What do you think?

**Comment by Be-ing** [comment]
Tao depends on GTK. Introducing a dependency on a large C library would IMO be a regression.

**Comment by tronical** [comment]
Perhaps we should also consider just supporting tao as an _additional_ backend, not necessarily replacing winit. As we've moved the renderers out of the winit backend this should be easier than it used to be.

**Comment by ogoffart** [comment]
Someone that wants to use a different backend than winit can always re-implement the backend using our platform API.
We don't intend to use tao ourselves at this point.
