### ISSUE TITLE
Make it possible to handle double clicks

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#2774]
### Discussed in https://github.com/slint-ui/slint/discussions/2772

<div type='discussions-op-text'>

<sup>Originally posted by **pcevent** May 24, 2023</sup>
How do I capture mouse double-click events?</div>

At the moment the internal mouse press and release events have a click count, which the built-in `Text` item uses to handle double clicks. We should either make this API public or design a new API to make it possible to handle double/triple/etc. clicking in Slint code.

**Comment by ogoffart** [comment]
Some things we could so:
 - expose the internal "click-count" in the PointerEvent
 - add a `double-clicked` callback to the TouchArea

I think we should do both eventually.
I have the feeling that in most cases user don't want the normal clicked handler to be run if (and only if) there is no double click. 

I believe we should do the following:
  - add a `double-clicked` callback to TouchArea
  - If there is a callback handler for double click, **do not send `clicked` immediately**,  but instead, start a timer of the double click internal, and then call the clicked, if there was no further click.

**Comment by tronical** [comment]
> I believe we should do the following:
> [ ... ]

I agree

> A multi-clicked callback with a click count argument is probably more generically useful. Someone will want to use a triple-click at some point :-)

I don't think it's necessary to go all the generic way. Honestly, with a mouse event double click is a rather rare pattern (even on Windows I'd say single click is dominant). With finger input double "tap" is not an established pattern IMO. With pencils a double click (on the pencil's button for example) is a good pattern, but I have yet to see a triple or n-click (n > 3).

I'm in favor of a pragmatic double-click and we can worry about a `multi-click` in the (unlikely) event that it becomes popular.

**Comment by tronical** [comment]
This was implemented in #4060 :-)

**Comment by ubruhin** [comment]
I encountered a limitation of the current pointer event concept and saw it was discussed here.

>> Expose the click count in the public pointer event:
>
>When doing a five-time click you get events with a click count of 1, 2, 3, 4 and 5 and have no idea whether the 5-event will eventually be followed by 6, 7, ... or not. That is not very useful, especially as we the timeout for "double clicks" is not exposed to the public as far as I can tell. So a user have no way to wait for the right amount of time to decide that my 5-event was indeed the last event to happen.

I think you're right for parts of the use-cases. But I also see use-cases where we don't need to know what was the final click count, because every click just switches to some next state. In the simple case of text selection, the first click moves the cursor, the second click selects the word, the third click selects the whole text. Every action can be taken immediately, without knowing the final click count. Or in a tool where graphical objects can be dragged, the first click selects an object, the second click enables resize handles, the third click enables rotation handles. Or the first click selects the object, the second click opens its properties (normal double-click behavior).

In LibrePCB we need such quite low-level access to pointer events (pressed, released, moved, including modifiers) to implement the graphics view. So the `TouchArea::pointer-event` callback is exactly what we need. However, currently it does not let me know when a double-click happened. The two workarounds are both not great:

- Either I could implement the `double-clicked` callback too. This has several drawbacks:
  - We'll get the "Down" event twice (once in `double-clicked` and once in `pointer-event`) in this sequence:
    1. Down
    1. Up
    1. Down <-- we don't know it was a double click, so it will be handled again as a single click
    1. Double-click
    1. Up
  - We don't know the keyboard modifiers
  - It's not available for right click (but I admit, double-right-click is not really a use-case)
- Or I could implement only `pointer-event` and detect double-clicks (or multi-clicks in general) on my own. This is not nice because the click delay is a system dependent value which should IMO be handled by the UI toolkit, not in user code.

I think the click count would solve this problem in a very powerful way as the resulting sequence of `pointer-event` would be:
1. Down 1
1. Up 1
1. Down 2
1. Up 2

Just for reference, IIRC the event sequence of Qt is:
1. Down
2. Up
3. Double-Click
4. Up

But unfortunately the sequence was not stable across all Qt5 versions, which caused headaches for me as a graphical application heavily relies on a stable pointer event system.
