### ISSUE TITLE
Accessibility: Add support for performing actions on elements

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#2872]
With accessibility APIs there are ways that assistive tech like screen readers can activate elements "programmatically". This is sometimes emulated by the system using a synthetic mouse click (VoiceOver on macOS seems to like doing that), but for example the AccessKit APIs have dedicated [actions](https://docs.rs/accesskit/latest/accesskit/enum.Action.html) that can be run, such as "Increment", "Decrement", "Expand", "Collapse", "ShowContextMenu", "SetValue" (slightly more generic), or even "Default" (presumably press on a Button, for example).

We should allow defining such actions in .slint and invoke them from the run-time library if the accessibility APIs request for their invocation.

Perhaps we can use implicit callbacks for this?

```slint
accessibility-action-expand => { my code here to expand }
accessibility-action-increment => { self.increment(); }
```

If such a callback is defined on an element, then we can report to the OS that this action is supported and invoke correspondingly.

**Comment by ogoffart** [comment]
I had some thought about it, here is what i think we need to do:

**Runtime:**

 - [ ] Add an (internal) `enum AccessibleAction{ Default, Expand, SetValue(f64), SetText(SharedString), ...} `
 - [ ] Add ad function in the ItemTreeVTable such as `fn accessible_action(Pin<VRef<ItemTreeVTable>>,  item_index: u32, ation: AccessibleAction)`
 - [ ] We also need an accessible_supported_actions function in the vtable that returns the set of supported action for an item. (as a `bitflags!`?)
 - [ ] In the winit and Qt backend, implement code that calls this accessible_action when coming from the accessible interface

**Compiler:**

 - [ ] Similar to the accessible-* property, add accessible-action-* callbakcs. They should take a parameter so that accessible-action-set-text would take a string.
 - [ ] Generate the `accessible_action` implementation in the ItemTree implementation, that calls the code for the given callback.
 - [ ] And generate the code for `accessible_supported_actions` based on what callback are being re-implemented

**Comment by ogoffart** [comment]
This was done in 1.6
