### ISSUE TITLE
Is Qt license required for commercial linux-app?

### ISSUE THREAD

**Issue by frehberg** [slint-ui/slint#2929]
On Linux  Slint may be using Qt-framework as backend.  

For a commercial app, does that mean  a commercial license is required for Qt ?

Is there an alternative to Qt for apps running on Linux?

**Comment by aurindam** [comment]
Slint has two backends: GL and Qt. 

- The GL backend uses the femtovg and winit crate for the rendering. 
- The Qt backend uses Qt. You would want to use the Qt backend if you need native style. Otherwise you can use the GL backend.

Reference: [Do I need to use Qt?](https://github.com/slint-ui/slint/blob/master/docs/install_qt.md#do-i-need-qt-to-use-slint)

**Comment by ogoffart** [comment]
Yes, the Qt backend is only recommended for the native style. So you don't need Qt at all in the case of full screen mode
(But even if you used the Qt backend, you still wouldn't need a commercial Qt license because of LGPL)

Note that in the case of app shipped together with embedded hardware, you need a Slint license.
