### ISSUE TITLE
SVG Rendering Performance

### ISSUE THREAD

**Issue by dngulin** [slint-ui/slint#3042]
I tried to use an SVG image as a window background and faced performance issues.

- Image rendering can take a lot of time. [This image](https://github.com/dngulin/gpcl/blob/dfcfafd93bb75bea2767b7552e0eb7e680e016a0/res/bg.svg) loads about one minute on my machine
- Window resizing is too slow and sometimes causes a crash `[ERROR smithay_client_toolkit::event_loop] Error trying to flush the wayland display: Broken pipe (os error 32)` even with a simpler background [image](https://github.com/dngulin/gpcl/blob/2da2249f5e996aedd0c4c80516961155d6c65899/res/img/bg.svg)

Is there any limitations with SVG images? I can try to get an image that doesn't use some SVG features.

Environment: Linux/KDE/Wayland
Slint version: 1.1.0
Language: Rust
Renderer: renderer-winit-femtovg

**Comment by dngulin** [comment]
I've converted this [svg image](https://github.com/dngulin/gpcl/blob/2da2249f5e996aedd0c4c80516961155d6c65899/res/img/bg.svg) into a [slint file](https://github.com/dngulin/gpcl/blob/2bede798b51e0de26f10cb1853a71ec9ee6ac325/res/background.slint) with path commands. Now it works without any performance issues.

If it is an expected behaviour, the issue can be closed.

**Comment by ogoffart** [comment]
Thanks for the bug report.  
We need to investigate this issue: it is not supposed to be so slow.

**Comment by tronical** [comment]
This is also reproducible in resvg itself: `cargo run /path/to/bg.svg test.png`

**Comment by tronical** [comment]
AFAICS the four gaussian blur filters applied in software on the 1920x1080 surface are taking the bulk of the time.

**Comment by tronical** [comment]
@dngulin I'm going to close this as wont fix for now on our end. I'm not sure there's much that we can do in the medium term. Long term perhaps we can eventually have a GPU based SVG renderer that can implement things like filters on many GPU cores, instead of a single-core software implementation.

Apart from the workaround you found (implement the paths with gradient fills in slint), pre-rendering the SVG into a PNG seems like a reasonable alternative to me, too.
