### ISSUE TITLE
Disabling ComboBox seems not to work properly

### ISSUE THREAD

**Issue by SKittan** [slint-ui/slint#3273]
I'm working with Slint and Rust on a Windows 11 machine.
When I set the `enabled ` property of a `ComboBox` to `false`, it's getting grayed out, but can still interact with.

[SlintPad ComboBox Example](https://slint.dev/releases/1.1.1/editor/?snippet=import+%7B+ComboBox+%7D+from+%22std-widgets.slint%22%3B%0Aexport+component+Example+inherits+Window+%7B%0A++++width%3A+200px%3B%0A++++height%3A+200px%3B%0A++++ComboBox+%7B%0A++++++++y%3A+50px%3B%0A++++++++width%3A+self.preferred-width%3B%0A++++++++height%3A+self.preferred-height%3B%0A++++++++model%3A+%5B%22first%22%2C+%22second%22%2C+%22third%22%5D%3B%0A++++++++current-value%3A+%22first%22%3B%0A++++++++enabled%3A+false%3B%0A++++%7D%0A%7D%0A)

**Comment by ogoffart** [comment]
Thanks a lot for your bug report.

This was already reported in #3126 , and i'm glad to say that this is already fixed in the master branch: 
[master verison](https://slint.dev/snapshots/master/editor/?snippet=import+{+ComboBox+}+from+%22std-widgets.slint%22%3B%0Aexport+component+Example+inherits+Window+{%0A++++width%3A+200px%3B%0A++++height%3A+200px%3B%0A++++ComboBox+{%0A++++++++y%3A+50px%3B%0A++++++++width%3A+self.preferred-width%3B%0A++++++++height%3A+self.preferred-height%3B%0A++++++++model%3A+[%22first%22%2C+%22second%22%2C+%22third%22]%3B%0A++++++++current-value%3A+%22first%22%3B%0A++++++++enabled%3A+false%3B%0A++++}%0A}%0A)

So i'm closing this issue as duplicated. But thanks anyway for reporting the bug.
