### ISSUE TITLE
How open a  new window in the main window ?

### ISSUE THREAD

**Issue by guobbs** [slint-ui/slint#3475]
I didn't find any examples in the slint demo that can open two windows at the same time, nor did I find a way to do so. 
How can I open a new window in the main window? For example: display message box dialog box, display pop-up window, etc.

I'm using Windows10/11 .

Thanks!

**Comment by ogoffart** [comment]
At the moment it is a bit complicated because each slint invocation only generate one window. See https://github.com/slint-ui/slint/issues/784
It is possible however if you use several slint! macros.
There is an example in this PR which uses another slint! macro to show a dialog:  https://github.com/slint-ui/slint/pull/2094

Closing this issue as it is already tracked in https://github.com/slint-ui/slint/issues/784 , but thanks anyway.
