### ISSUE TITLE
Combox in native style is not shown 

### ISSUE THREAD

**Issue by legath** [slint-ui/slint#3527]
```
import { Button, VerticalBox, ComboBox } from "std-widgets.slint";
export component AppWindow inherits Window {
    width: 800px;
    height: 600px;
    VerticalBox {
        alignment: start;
        Text {
            text: "Hello World!";
            font-size: 24px;
            horizontal-alignment: center;
        }
        ComboBox {
            height: self.preferred-height;
            width: self.preferred-width;
            enabled: true;
            model: ["first", "second", "third"];
            current-value: "first";
            }
    }
}
```

_OS: Manjaro Linux x86_64 
Kernel: 6.1.49-1-MANJARO 
Resolution: 3440x1440 
DE: Xfce 4.18 
WM: Xfwm4 
WM Theme: Matcha-sea 
Theme: Matcha-sea [GTK2], Adwaita [GTK3] 
CPU: Intel Xeon E5-2697 v2 (48) @ 3.500GHz 
GPU: NVIDIA GeForce RTX 3070 
Memory: 28767MiB / 64228MiB_ 

_QMake version 3.1
Using Qt version 5.15.10 in /usr/lib_

```
[dependencies]
slint = "1.2.1"

[build-dependencies]
slint-build = "1.2.1"
```

![2023-09-22_01-12](https://github.com/slint-ui/slint/assets/400612/95745164-6bb8-43b3-963d-bdc37c54cb62)
![2023-09-22_01-13](https://github.com/slint-ui/slint/assets/400612/7e338da9-b4e0-42d1-9ea0-4ad1db85cee6)

**Comment by ogoffart** [comment]
Thanks for the bug report

The problem is this:
```
            height: self.preferred-height;
            width: self.preferred-width;
```

But the native style's code only sets the minimum size and not the maximum size. 
The layout engine makes sure that works by clamping the preferred size within the bounds.  But when accessing the preferred-* property directly this doesn't work anymore

The workaround is to use `minimum-height` and `minimum-width` for now.
