### ISSUE TITLE
Feature Request: Customizable Slider 

### ISSUE THREAD

**Issue by frehberg** [slint-ui/slint#3546]
Builtin Slider Element cannot be customized to work properly  as volume control or heat regulation.  right now orientation can be changed only, and direction is limited to left-to-right and top-to-bottom

I would like to see a customizable slider,

* changing orientation: horizontal, vertical 
* changing direction of growing bar: eg growing bottom-up
* changing width of bar
* changing design of slider-handle

**Comment by ogoffart** [comment]
Thank you for submitting a bug report.

> changing orientation: horizontal, vertical

This is already implemented. The Slider has an `orientation` property since Slint 1.2.


The rest is not there yet, and i don't know if it makes sense in our standards widgets. But we have documentation on how to implement custom slider: https://slint.dev/releases/1.2.1/docs/slint/src/recipes/recipes#customslider
