### ISSUE TITLE
TextInput caret is renderer at wrong position with non-default alignment

### ISSUE THREAD

**Issue by ilmai** [slint-ui/slint#3580]
If TextInput horizontal-alignment is center or right, caret is still rendered at the left edge when there's no text. Pictures show this better, see below.

Empty text:
<img width="73" alt="image" src="https://github.com/slint-ui/slint/assets/3365471/a3466b8f-813e-40c9-897d-becab7320ebf">

After typing "a":
<img width="73" alt="image" src="https://github.com/slint-ui/slint/assets/3365471/f21ac8a1-d193-4370-b03b-872adbe6df13">

**Comment by Areopagitics** [comment]
I am pretty sure there is a regression on this in 1.14.1. I'm using skia renderer. Same goes for LineEdit.

You can easily test it with:

```
export component AppWindow inherits Window {
    width: 300px;
    height: 80px;

    TextInput {
        width: 200px;
        height: 40px;
        horizontal-alignment: center;
    }
}
```

**Comment by ogoffart** [comment]
Indeed, I can reproduce with both Skia and femtovg and software.  (Qt is fine)

**Comment by ogoffart** [comment]
Reported upstream https://github.com/linebender/parley/issues/534

**Comment by ogoffart** [comment]
Upstream issue closed. Thank you.

**Comment by Nubuki-all** [comment]
> Upstream issue closed. Thank you.

It still happens on Android with horizontal-alignment: right; (empty text or otherwise)

Landscape 
<img width="2400" height="216" alt="Image" src="https://github.com/user-attachments/assets/533a445c-4716-4906-8428-34040e37f417" />
Portrait 
<img width="1080" height="387" alt="Image" src="https://github.com/user-attachments/assets/5b07c69c-2b74-46ba-81b1-ca2d68423e51" />

@ogoffart
