### ISSUE TITLE
Items are sorted by name when adding model in rust

### ISSUE THREAD

**Issue by qarmin** [slint-ui/slint#3724]
When using project with model set inside slint file, everything works fine

![Screenshot from 2023-10-21 15-24-09](https://github.com/slint-ui/slint/assets/41945903/53a7b918-f515-4471-8acc-c608e0da79ba)

but when setting it via rust, then instead setting 3 bools in original order from slint file (checked, selected, header), it is saved in sorted? order(checked, header, selected)

![Screenshot from 2023-10-21 15-24-30](https://github.com/slint-ui/slint/assets/41945903/e4edaca9-911a-42d8-973d-289b05060a29)

Test project - [slint-rust-template.zip](https://github.com/slint-ui/slint/files/13060793/slint-rust-template.zip)

**Comment by ogoffart** [comment]
Yes, this is documented in  https://docs.rs/slint/latest/slint/docs/type_mappings/index.html

I'm afraid we need to normalize the order somehow. And this is then done using the order.

I recommand you to use a named `export struct  NamedStruct { checked: bool,  selected_row: bool, header_row: bool}` instead of an anonymous struct when using it as a property type.
