### ISSUE TITLE
Linear gradient angle is wrong in non-square areas

### ISSUE THREAD

**Issue by plule** [slint-ui/slint#3730]
Hello. When creating a linear gradient at an angle, the angle is changing depending on the area dimensions, and inconsistent between backends.

```slint
export component AppWindow inherits Window {
    background: @linear-gradient(45deg, black 0%, black 49%, white 51%, white 100%);
}
```

This should make a visible 45deg transition, but the angle varies between backends:

Default renderer:
![image](https://github.com/slint-ui/slint/assets/630159/b79fed56-9ce8-46d2-a772-5124d05b16b2)

Skia:
![image](https://github.com/slint-ui/slint/assets/630159/763088f8-4598-4c66-9de0-0d65ea676609)

OS: Windows
Slint: 1.2.2

**Comment by tronical** [comment]
AFAICS the FemtoVG renderer gets it wrong, while Qt and Skia get it right. The software renderer doesn't support gradients on the Window's background brush yet.

**Comment by ogoffart** [comment]
This is how it renders on the web (notice it should be 45°)
![image](https://github.com/slint-ui/slint/assets/959326/78576cd9-2c69-44be-ba27-27781e7d8ae9)

Femtovg:   angle is less than 45°
![image](https://github.com/slint-ui/slint/assets/959326/62436be7-ffb1-4634-ab48-322cd776577b)

Skia: Angle is more than 45°
![image](https://github.com/slint-ui/slint/assets/959326/c63a9140-2d22-40e0-8fc7-dbc0647e221b)

Qt: same as skia 
![image](https://github.com/slint-ui/slint/assets/959326/4b0423c1-4fc8-4f87-bd47-7a86235b55fe)

Software renderer  (angle is correct but there is an artifact though)
![image](https://github.com/slint-ui/slint/assets/959326/f1e439f4-2128-4b06-8822-ff874bd1dc98)

Note that i added an extra Rectangle from the testcase because software renderer don't support gradiant on window)
