### ISSUE TITLE
MacOS: Terminal opens with application

### ISSUE THREAD

**Issue by apertureless** [slint-ui/slint#4004]
# Issue

When you open (double-click) the application on MacOS, it additionally opens a terminal window where it executes the binary.

![image](https://github.com/slint-ui/slint/assets/4975917/20c3a43d-be8a-40fe-ab72-f09152765a38)

## Reproduction

- `cargo generate --git https://github.com/slint-ui/slint-rust-template --name slint-test`
- `cargo build --release`
- `open target/release` 
- Double click on `slint-test`

## System

Tested on MacOS Ventura (13.6.1)

**Comment by FloVanGH** [comment]
Hi and thank you for your report.

This is default behavior on macOS binaries. This happens if you open by double click a "simple" binary. You can check this if you open a binary file inside of a `.app` with double click. Or you can try it building an other project and running the binary by double click.
