### ISSUE TITLE
Multi-window support ?

### ISSUE THREAD

**Issue by shanliu** [slint-ui/slint#4031]
How to create multiple windows in the desktop environment?

**Comment by ogoffart** [comment]
If this is about several instance of the same windows, you can just use `MyWindow::new()`  several time and call `.show()` on multiple window.

If you need several window of different kind,  you currently need to use the `slint!` macro several time. The problem is that they are all independent from eachother and don't share the datastructure and all.  (and it is also not possible with slint-build yet  https://github.com/slint-ui/slint/issues/3217 )

In the future we plan to support multiple component from the same file:  
https://github.com/slint-ui/slint/issues/784
