### ISSUE TITLE
When wrapping a TextInput, the binding does not work

### ISSUE THREAD

**Issue by Pilyushkin** [slint-ui/slint#4072]
Hello. I'm trying to make a field for entering numbers, but the entered value is not updated (the location is indicated in the code). What could be the reason?

slint = "1.2" 

```
slint::slint!{
component Wrapper inherits Rectangle {
        border-color: blue;
        border-width: 1px;
        in-out property <string> text <=> text.text;
        callback edited <=> text.edited;
        text := TextInput {}
    }

   
    export component Test {
        in-out property <float> text: 6.5;
        callback edited();

        VerticalLayout {
            Text {
                text: "text -> " + text;  // Why is the text not updating?
            }

            Wrapper {
                text: root.text;
                edited => {
                    debug("self text: ", self.text);
                    root.text = self.text.to-float();
                }
            }
        }
    }
}

fn main() {
    let test = Test::new().unwrap().run().unwrap();
}
```

**Comment by tronical** [comment]
Hmn, is it possible that this is fixed in a newer version of Slint? It works for me on [SlintPad](https://slintpad.com/?snippet=component+Wrapper+inherits+Rectangle+%7B%0A++++++++border-color%3A+blue%3B%0A++++++++border-width%3A+1px%3B%0A++++++++in-out+property+%3Cstring%3E+text+%3C%3D%3E+text.text%3B%0A++++++++callback+edited+%3C%3D%3E+text.edited%3B%0A++++++++text+%3A%3D+TextInput+%7B%7D%0A++++%7D%0A%0A+++%0A++++export+component+Test+%7B%0A++++++++in-out+property+%3Cfloat%3E+text%3A+6.5%3B%0A++++++++callback+edited%28%29%3B%0A%0A++++++++VerticalLayout+%7B%0A++++++++++++Text+%7B%0A++++++++++++++++text%3A+%22text+-%3E+%22+%2B+text%3B++%2F%2F+Why+is+the+text+not+updating%3F%0A++++++++++++%7D%0A%0A++++++++++++Wrapper+%7B%0A++++++++++++++++text%3A+root.text%3B%0A++++++++++++++++edited+%3D%3E+%7B%0A++++++++++++++++++++debug%28%22self+text%3A+%22%2C+self.text%29%3B%0A++++++++++++++++++++root.text+%3D+self.text.to-float%28%29%3B%0A++++++++++++++++%7D%0A++++++++++++++++height%3A+28px%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D&style=native). After entering text in the bottom field, it shows - provided that it's a number.

**Comment by Pilyushkin** [comment]
I checked it on version 1.74, it doesn’t work. Preview works in the visual studio code with slint plugin.
OS - ubuntu 22.04

**Comment by Pilyushkin** [comment]
slint = "1.3.2"
rustc = 1.74
