### ISSUE TITLE
preview: preferred size must not be between the minimum and maximum size.

### ISSUE THREAD

**Issue by hunger** [slint-ui/slint#4075]
The preview renders the embedded component at its preferred size, without clamping to the minimum and maximum sizes.

This is different from what the actual window will do: That does apply clamping.

This is an example where you can observe the difference in behavior between Slint preview and a slint window:

```slint
export component MainWindow inherits Window {
    preferred-width: 100px;
    preferred-height: 100px;

    VerticalLayout {
        Rectangle {
            background: Colors.red;
            width: 50px;
            height: 50px;
        }
    }
}
```

**Comment by ogoffart** [comment]
Fixed in master

[link](https://slint.dev/snapshots/master/editor/?snippet=import+{+AboutSlint%2C+Button%2C+VerticalBox+}+from+%22std-widgets.slint%22%3B%0A%0A%0Aexport+component+MainWindow+inherits+Window+{%0A++++preferred-width%3A+100px%3B%0A++++preferred-height%3A+100px%3B%0A%0A++++VerticalLayout+{%0A++++++++Rectangle+{%0A++++++++++++background%3A+Colors.red%3B%0A++++++++++++width%3A+50px%3B%0A++++++++++++height%3A+50px%3B%0A++++++++}%0A++++}%0A}&style=native)
