### ISSUE TITLE
Cannot find default fonts in GNU Guix.

### ISSUE THREAD

**Issue by jeandudey** [slint-ui/slint#4077]
I'm using Slint with Rust 1.70 on GNU Guix.

When trying to run `examples/todo/rust` it panics on startup because Slint is not able to find the DejaVu fonts on the system (installed).

This error can be reproduced on a GNU Guix system as follows:

```bash
guix shell --pure font-dejavu \
                  fontconfig \
                  gcc-toolchain \
                  wayland \
                  libx11 \
                  libxcursor \
                  libxi \
                  libxkbcommon \
                  pkg-config \
                  rust \
                  rust:cargo -- \
                  cargo run --manifest-path examples/todo/rust/Cargo.toml
```

And shows the following output:

```
warning: Could not find a Qt installation. The Qt backend will not be functional. See https://github.com/slint-ui/slint/blob/master/docs/install_qt.md for more info
warning:     Failed to execute qmake. Make sure \'qmake\' is in your path!\nentity not found
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/todo`
thread 'main' panicked at 'Unable to determine default font. Failed to locate font for family DejaVu Sans', internal/common/sharedfontdb.rs:151:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The `XDG_DATA_DIRS` environment variables inside of the guix shell:

```
...
declare -x XDG_DATA_DIRS="/gnu/store/3722lq2qa7wwqpzphn22xngvfbd3ci5p-profile/share"
```

Which contains the DejaVu fonts at `/gnu/store/3722lq2qa7wwqpzphn22xngvfbd3ci5p-profile/share/fonts/truetype`:

```
DejaVuMathTeXGyre.ttf
DejaVuSans-Bold.ttf
DejaVuSans-BoldOblique.ttf
DejaVuSans-ExtraLight.ttf
DejaVuSans-Oblique.ttf
DejaVuSans.ttf
DejaVuSansCondensed-Bold.ttf
DejaVuSansCondensed-BoldOblique.ttf
DejaVuSansCondensed-Oblique.ttf
DejaVuSansCondensed.ttf
DejaVuSansMono-Bold.ttf
DejaVuSansMono-BoldOblique.ttf
DejaVuSansMono-Oblique.ttf
DejaVuSansMono.ttf
DejaVuSerif-Bold.ttf
DejaVuSerif-BoldItalic.ttf
DejaVuSerif-Italic.ttf
DejaVuSerif.ttf
DejaVuSerifCondensed-Bold.ttf
DejaVuSerifCondensed-BoldItalic.ttf
DejaVuSerifCondensed-Italic.ttf
DejaVuSerifCondensed.ttf
fonts.dir
fonts.scale
```

When running with `export SLINT_DEFAULT_FONT=/gnu/store/3722lq2qa7wwqpzphn22xngvfbd3ci5p-profile/share/fonts` it works fine though.

**Comment by tronical** [comment]
I can't run the command unfortunately :-(. Somehow it picks a really old version 1.60 of cargo/rust for me, which fails to parse our Cargo.toml files. If I remove the `--pure` and pick up my local rust/cargo, I get linking errors.

I was able to create an interactive guix-shell though to inspect the environment. I'm afraid our hands are a little tied here: At the heart of the problem is that while libfontconfig is built to look in Guix specific places for fonts, we're not using fontconfig directly but we're merely looking in standard locations such as /etc/fonts/fonts.conf and a few other places. The code in question is here:

    https://github.com/RazrFalcon/fontdb/blob/c3274d016cad92fac744d76a91e4554fe51c5745/src/lib.rs#L425

If Guix was setting `XDG_CONFIG_HOME` then we'd find the right fonts.conf perhaps. Alternatively, perhaps you could point `FONTCONFIG_FILE` in your environment to the Guix path? (for me that's for example `/gnu/store/1vxl2hcqdpr4n359addyq0iai3bd2cr7-fontconfig-2.13.94/etc/fonts/fonts.conf`, but obviously that's not a generic path :)

On second thought, I think this is best fixed in Guix if the fontconfig package would set the `FONTCONFIG_FILE` environment variable (documented upstream at https://www.freedesktop.org/software/fontconfig/fontconfig-user.html )

**Comment by tronical** [comment]
Thanks for the explanations. This makes sense to me. I do agree with your analysis and I think that fontdb ideally should support `XDG_DATA_DIRS` then.

**Comment by mskiptr** [comment]
I'm just a passerby trying to figure out how system fonts are detected "in the wild", but this got me thinking. Unless you were using a Guix-packaged `slint` (in which case the package should provide the required environment), how would you want that font to be found? I see a few options:

- use `fontconfig` from `$PATH` and tell the user to provide that
- search through `${XDG_DATA_{HOME,DIRS}}/fonts` and task the user with setting it up
- require the user to explicitly configure the font location (via an environment variable, some config file, etc.)

But it looks like `slint` does some of that already. Or have I misunderstood the problem? Were you reporting that it does not look in `XDG_DATA_*` even if that's set correctly?

**Comment by tronical** [comment]
Yes, I think the problem here is that the lookup we're doing isn't quite exactly what fontconfig is doing. See also https://github.com/slint-ui/slint/issues/4077#issuecomment-1849844844 . The good news is that we're in the process of migrating to fontique for the font discovery, which - in the very latest version we're working on upgrading to - introduces a direct dependency and use of fontconfig, for a fully compliant discovery.
