### ISSUE TITLE
Provide Pythonic Slint in the PyPI

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#4138]
A key reason for Python’s popularity is how easy it is to share and re-use Python modules across projects. The objective of this task is to make it possible to use Slint in a Python project by making Slint available in the Python Package Index.

Proposed sub-tasks:

 - [x] The initial milestone covers packaging Slint for use on PyPI in a way that installation will build Slint from source. In principle this milestone should be straight-forward, but as often with generic build instructions, the details tend to be complex, and this milestone also covers documenting system prerequisites that need to be fulfilled before the build can succeed.
 - [x] Building Slint from source requires certain various Rust/C development tools to be installed on the system. For convenience, this task tries to cover providing binary wheels for macOS.
 - [x] Provide Slint binary wheels for Windows.
 - [x] Provide Slint binary wheels for common Linux setups
 
 
 This work will be sponsored by the [NLnet foundation](https://nlnet.nl/project/PythonicSlint/).

**Comment by tronical** [comment]
All binaries packages are built as abi3 with cpython 10, linux against manylinux_2_35 for aarch64, armv7, and x86-64.

We can continue to tweak this going forward and based on feedback, but this seems like a reasonable starting point.

**Comment by tronical** [comment]
Binaries and sources are now on https://pypi.org/project/slint/

**Comment by hyuri** [comment]
Android [and iOS] wheels are missing. Should be included in this issue, right?

Mobile wheels is a new development, but it's becoming official in PyPI and cibuildwheels. I've been told by the BeeWare team that mobile support in cibuildwheel is ready for iOS and in-progress for Android (should come within a month or so).
https://www.anaconda.com/blog/beeware-mobile-python

For reference, this is the first project in the PyPI to provide Android and iOS wheels, to demonstrate these capabilities:
https://pypi.org/project/pyspamsum/1.0.7/#files

**Comment by freakboy3742** [comment]
> (I've been using beeware's amazing tools to verify that it works).

BeeWare maintainer here - FWIW, it's possible to write a plugin to Briefcase so that Slint support is available as a bootstrap option. Briefcase ships with some built-in plugins, but our preference would be for third party toolkits to take ownership of their own plugins (as they're going to be the experts on how those toolkits can/should be used).

The [Toga-positron](https://github.com/beeware/toga/tree/main/positron) bootstrap is an example of this in practice (providing a "Toga but with some other design options" starting point for new projects. If you need any pointers on how to set this up, let us know.
