### ISSUE TITLE
Meta and control key switched on mac

### ISSUE THREAD

**Issue by Kees-van-Beilen** [slint-ui/slint#4335]
Using:*macOS 13.14 M1 8GB MacBook Pro (Keyboard Layout: NL); Rust* 
I have found that the Meta or on macOS the ⌘-key has been switched around with the control key. 
In a focus group, when pressing ⌘: e.modifiers.control returns true whilst when pressing ^: e.modifiers.meta returns true.
Obviously this behaviour should be switched. 

*A snippet that can be used to reproduce this behaviour:*
```slint
export component AppWindow inherits Window {
  FocusScope {
     key-pressed(e) => {
        debug(e)
     }
  }
}
```
Can other mac user confirm if this for them is also the case?

**Comment by tronical** [comment]
Yes, this is an intentional mapping to make it easier to develop cross platform apps:

On Windows and Linux, commands typically start with the control modifier (such as CTRL+C), while on macOS they typically start with Command (command+c)

To avoid having to write conditionals in .slint code depending on the operating system, we're swapping command and control.

Sadly, our documentation doesn't match the behavior implemented with the Qt and the winit backend :-(

We could consider changing this though, through a flag of sorts.

How would you like this to be written in your Slint code?

**Comment by tronical** [comment]
Yes, I think the acceptance criteria here is to fix the docs. Any other suggestions Olivier/Tobias?

**Comment by ogoffart** [comment]
I think I voiced before (although i don't find references to these discussions) that IMHO the "control" should be the key that's written on the keyboard as "control" and that we shouldn't do some inversion. Instead provide some other ways to define keyboard shortcut in a cross platform way. But these discussions were long ago anyway and there were also good arguments for swapping.
