### ISSUE TITLE
Dark/Light mode detection on Linux with winit is unreliable 

### ISSUE THREAD

**Issue by qarmin** [slint-ui/slint#4392]
As a fan of the dark mode, the default bright mode is not very friendly to my eyes.

It would be useful to add a dark background

![Screenshot from 2024-01-21 14-53-14](https://github.com/slint-ui/slint/assets/41945903/a0706034-87f6-4d21-8ec0-7d4492e0b48e)

Edit: While the contrast issue is fixed, the issue that remains here is that with winit we don't get notified when the theme changes on Linux. See also https://github.com/rust-windowing/winit/issues/1549

**Comment by tronical** [comment]
Odd, for me the toolbar with the pick mode button and the combobox looks okay (macOS). But the area around the preview'ed UI is unconditionally white:

```
background: root.experimental ? Colors.pink : Colors.white ;
```

I guess that should be `Palette.background` instead? @FloVanGH : Or should it be another one of the alternate backgrounds?

**Comment by tgrushka** [comment]
Light-sensitive legally blind developer here. Please support dark mode. Someone just removed dark-light detection on Linux to save 1/6 of their compile time. Accessibility should be on by default, not off by default. Dark mode is part of accessibility. It should at least default to dark mode if you're going to remove detection, because most other apps are now defaulting to dark mode.

Make dark-light part of the default feature set. Flag it as a feature. Then, devs will have to explicitly remove it. Sadly, they will just to save compile time in development, and forget to turn it on in production, because accessibility is always an afterthought. But it's better than turning it off for everyone.

**Comment by KamWithK** [comment]
Is there at the least some kind of environment variable or LSP arg to use dark mode with a dark background?
