### ISSUE TITLE
Text in documentation is cutoff.

### ISSUE THREAD

**Issue by Mintype** [slint-ui/slint#4964]
Link to the doc page: https://slint.dev/releases/1.5.1/docs/slint/src/language/widgets/lineedit#lineedit

![image](https://github.com/slint-ui/slint/assets/96578565/9e9264d2-0259-4752-aa77-3ab48c9dd048)

Here it gets cut off at "but".

In the code it says: 
![image](https://github.com/slint-ui/slint/assets/96578565/713ba03c-27bd-4991-b33e-e25ecf055d0c)

**Comment by ogoffart** [comment]
Thanks for reporting the bug.
There was an error in the docs, but it was noticed recently and fixed in https://github.com/slint-ui/slint/commit/9885c4744ad2b175fc85826439a16077ea960675 which was fixed after the last release. Which is why you noticed the docs in the source is correct, but not online. The snapshot docs are fixe:
https://slint.dev/snapshots/master/docs/slint/src/language/widgets/lineedit#lineedit

Thanks anyway for reporting.
