### ISSUE TITLE
Name of special element ids (root, self)

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#50]
There are currently three reserved element id:

* `root` always refers to the component itself
* `self` always refers to the element in which the binding is in
* `parent` refers to the parent of `self`

We got feedback that `root` was confusing because it is ambiguous whether it refer to the application root (i.e, the `Window`) or to the element root.

Since we cannot give a custom name to the component root element, we need a keyword name to access it.
Potential suggestions would be to use `self` for the component root, and `this` for the element contained in the binding. or vice versa. or use `component` instead or `root`.

**Comment by tronical** [comment]
Three suggestions came out of a discussion so far:

1. Rename current `root` to `self`  (or `this`) and remove the old `self` by replacing every use with named components.
   Upside: `root` is not a reserved name anymore.
   Downside: `self` is not referring to the immediate surrounding instance anymore.

2. Use `@` (and potentially `@@`) to navigate through the different levels. So that'd be for example `@.width` to refer to the `width` of the component.

3. Rename `root` to `component` or `comp` since that is what it really refers to.

**Comment by ogoffart** [comment]
We decide to stay with the `self` and `root`. We've not gotten more feedback that this was confusing, and it kind of worked well so far
