### ISSUE TITLE
`animate background` has an unexpected bounce effect

### ISSUE THREAD

**Issue by mitioshi** [slint-ui/slint#5055]
When doing
```
animate background {
    duration: 1.0s;
    easing: ease-in-expo;
}
```

### Actual
background has a rebound/bounce effect with any easing setting(e.g. linear, ease-in-*, ease-out-*). 
Here's how it looks in action:
https://github.com/slint-ui/slint/assets/19928439/719ef91c-e652-4a28-b207-b9ece3ab8f2b

The background of this component should go from `transparent` to `lightgray` with the animate setting the same as the one above. The little square on the left is lightgray. In this video, you can see that the background shortly becomes darker than the little square (of target color) and then bounces back to lightgray (target color)

### Expected
The transition shouldn't have any bouncing.

## Minimal Reproducible Example
```slint

component Foo inherits Rectangle {
    background: transparent;

    states [
        hovered when touchArea.has-hover: {
            background: lightgray;
        }
    ]

    animate background {
        duration: 1.0s;
        easing: linear;
    }

    touchArea := TouchArea { }
}
```

### Environment
OS: EndeavourOS Linux x86_64
Kernel: 6.8.5-arch1-1
DE: Plasma 6.0.3
GPU: Intel HD Graphics 630 
GPU: NVIDIA GeForce GTX 1050 Mobile 
rustc: 1.77.2
Backend: winit
Renderer: skia (also reproducible on femtovg)
Slint: v1.5.1

**Comment by ogoffart** [comment]
The problem here is the interpolation between transparent and some color. It linearly interpolate both the alpha value, and also the color values. But that's wrong because then the "black" color of transparent shows a bit.

Note that `.mix` uses a different lagorithm 

This example ([slintpad](https://slintpad.com/?snippet=export+component+Foo+inherits+Window+%7B%0A++++min-height%3A+100px%3B%0A++++min-width%3A+500px%3B%0A++++background%3A+transparent%3B%0A++++HorizontalLayout+%7B%0A++++++++Rectangle+%7B%0A++++++++++++background%3A+transparent%3B%0A++++++++++++states+%5B%0A++++++++++++++++hovered+when+touchArea.has-hover%3A+%7B%0A++++++++++++++++++++background%3A+lightgray%3B%0A++++++++++++++++%7D%0A++++++++++++%5D%0A%0A++++++++++++animate+background+%7B%0A++++++++++++++++duration%3A+1.0s%3B%0A++++++++++++++++easing%3A+linear%3B%0A++++++++++++%7D%0A++++++++%7D%0A%0A++++++++Rectangle+%7B%0A++++++++++++property+%3Cfloat%3E+value%3B%0A++++++++++++background%3A+lightgray.mix%28transparent%2C+value%29%3B%0A++++++++++++states+%5B%0A++++++++++++++++hovered+when+touchArea.has-hover%3A+%7B%0A++++++++++++++++++++value%3A+1%3B%0A++++++++++++++++%7D%0A++++++++++++%5D%0A%0A++++++++++++animate+value+%7B%0A++++++++++++++++duration%3A+1.0s%3B%0A++++++++++++++++easing%3A+linear%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%0A++++%0A%0A++++touchArea+%3A%3D+TouchArea+%7B+%7D%0A%7D&style=native)) shows the difference between the mix and the animation
```slint
component Foo inherits Rectangle {
    background: transparent;

    states [
        hovered when touchArea.has-hover: {
            background: lightgray;
        }
    ]

    animate background {
        duration: 1.0s;
        easing: linear;
    }

    touchArea := TouchArea { }
}
```

**Comment by ogoffart** [comment]
This is the wrong function: 
https://github.com/slint-ui/slint/blob/2c0ba2bc0f151eba8d1fa17839fa2ac58832ca80/internal/core/graphics/color.rs#L306
It is implemented by linearly change all fields, which doesn't work with alpha values.

Instead of doing that, it should call `self.mix(target_value, t)` of the opposite

**Comment by mitioshi** [comment]
Seems like the fix is trivial. I'll submit a PR that uses `mix` for color interpolation

**Comment by mitioshi** [comment]
@ogoffart I submitted a PR with the suggested changes here: https://github.com/slint-ui/slint/pull/5063

**Comment by ogoffart** [comment]
Fixed by https://github.com/slint-ui/slint/pull/5063
Thanks @mitioshi
