### ISSUE TITLE
Slint has been in contact for a week, summarizing the issues

### ISSUE THREAD

**Issue by Dovelong0713** [slint-ui/slint#5174]
I hope to write a laptop program that I like and learn Rust through it. I chose Slint to implement it
But I encountered some difficulties, and if SLIT supports the following implementations, I can focus on the main logic of the laptop
 
1. TextInput/TextEdit:

Underline
Delete Line
Highlighted text segment
Keyboard Text
mathematical formula 
Superscripts and Subscripts 
Revoke and Redo

2. Image:

Image can be selected. For example, within a Rectangle, I can select it to implement drag logic
When the Image resource does not exist, there is a placeholder status prompt
 

3. Callback function for TouchArea has hover;
Callback function when states are satisfied

4. The pain of StandardTableView is that it cannot click to edit the table content

**Will there be a plan to improve the above features, or will you provide me with tips or ideas to implement them**
 

I also encountered some bugs:
TextInput input. The point should display a small dot, but it is actually a small square
The emoji in TextInput is gray
As described in # 5089, TextInput will not automatically obtain initial focus
When TextInput switches between desktop windows, without keyboard operation, TextInput will fill in the string itself
My environment is Windows 10, slim 1.5.1
![PixPin_2024-05-04_13-22-22_proc](https://github.com/slint-ui/slint/assets/140436474/b32fb709-a4a1-4974-b2e9-efe75c7bb4d7)

https://github.com/slint-ui/slint/assets/140436474/6c123b43-0309-4f93-a970-5be5ccdd176b

**Comment by ogoffart** [comment]
This issue is a bit difficult to handle as it puts lots of things together.


>  1. TextInput/TextEdit:
>
> Underline
> Delete Line
> Highlighted text segment
> Keyboard Text
> mathematical formula
> Superscripts and Subscripts

This would be richtext support (tracked in #2723)

> Revoke and Redo

There is undo/redo support since Slint 1.5

> 2. Image:
>
> Image can be selected. For example, within a Rectangle, I can select it to implement drag  logic
>When the Image resource does not exist, there is a placeholder status prompt

Not sure if there is need for anything in Slint for that.

> 3. Callback function for TouchArea has hover;

I think the `moved` callback is that.
Otherwise a changed callback is planed in  #112

> Callback function when states are satisfied

Will also be possible with #112

> 4. The pain of StandardTableView is that it cannot click to edit the table content

We would like to make it editable (tracked in https://github.com/slint-ui/slint/issues/2042 )

> Will there be a plan to improve the above features, or will you provide me with tips or ideas to implement them

You can find more information on the different issues. 
And yes, we're open to discuss and give tips. Please open discussion or issue specific to one topic.  You can also chat on chat.slint.dev

> I also encountered some bugs:

Looks like these have been filled separately: #5172 #5158

----

I'll close this issue since it is not actionable. Please open separate issue for different bug. Or use the discussions to ask questions.
