### ISSUE TITLE
Moving a named element produces a syntax error

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#5195]
Steps to reproduce:

1. Open https://snapshots.slint.dev/master/editor/
2. Give the `Text` element in the hello world a name:

```slint
import { AboutSlint, Button, VerticalBox } from "std-widgets.slint";
export component Demo {
    VerticalBox {
        alignment: start;
        new-name-given := Text {
            text: "Hello World!";
            font-size: 24px;
            horizontal-alignment: center;
        }
        AboutSlint {
            preferred-height: 150px;
        }
        HorizontalLayout { alignment: center; Button { text: "OK!"; } }
    }
}
```

3. Select "Design Mode" in the live-preview's toolbar.
4. Drag the "Hello World!" text label in the live-preview and drop it further down in one of the drop areas marked with a green line.

Observe how the `Text { ... }` element is moved, but the `new-name-given :=` part is left in the original place, resulting in a syntax error.

**Comment by ogoffart** [comment]
Moving/removing an element with an id shouldn't be a problem.  The problem is moving elements into another scope. if either the element itself uses it, or it is used and ends up in another scope.

So it is a problem if
 - the moved element has bindings that references `parent` (these could be rewritten)
 - the moved element has bindings that references something in its old scope which is no longer in the new scope (this operation should be disallowed?)
 - Some other element reference the moved element which is moved in another scope (this operation should be disallowed?)
 
When disallowing, a message should explain why.

**Comment by tronical** [comment]
> When disallowing, a message should explain why.

It would be nice to visualise the area of the scope. So a repeated element itself isn't movable, a child (or grand-child) of the repeated element should be movable within the area of the scope element's area. Everything outside could perhaps be visually masked (like grey'ed out), but definitely not accepted as drop location.
