### ISSUE TITLE
manual edits of line_edit break callbacks

### ISSUE THREAD

**Issue by sedan-cell** [slint-ui/slint#5303]
when a `line_edit` is manually edited by the user any associated callbacks break and no longer function.

minimal example:

`main.slint`
```
import {Button, LineEdit, VerticalBox} from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "callback-break";
    callback generate-clicked();
    in-out property <string> user-input;
    VerticalBox {
        LineEdit {
            input-type: text;
            text: root.user-input;
            edited => {
                root.user-input = self.text;
            }
        }
        Button {
            text: "Generate";
            clicked => {
                root.generate-clicked();
            }
        }
    }
}
```

`main.rs`:
```
slint::include_modules!();

use rand::{distributions::Alphanumeric, thread_rng, Rng};

fn main() -> Result<(), slint::PlatformError> {
    let app_window = AppWindow::new().unwrap();

    let ui_handle = app_window.as_weak();
    ui_handle.unwrap().set_user_input(generate_clicked().into());
    let ui_handle = app_window.as_weak();
    app_window.on_generate_clicked(move || {
        let app_window = ui_handle.unwrap();
        app_window.set_user_input(generate_clicked().into());
    });

    app_window.run()
}

fn generate_clicked() -> String {
    thread_rng()
        .sample_iter(&Alphanumeric)
        .map(char::from)
        .take(8)
        .collect::<String>()
}
```

screenshot:
![slint-demo_JOcVedGNhm](https://github.com/slint-ui/slint/assets/168591260/5e733483-75e1-4768-a3c9-f95cb275cb3c)

**Comment by Vadoola** [comment]
In your LineEdit trying changing

`text: root.user-input;`

into
`text <=> root.user-input;`

See if that solves your issue. I'm not sure and don't have time to test this, but I'm thinking since text on the LineEdit isn't set to to a 2 way binding, when you are updating LineEdit manually it's updating internally but not updating the root.user-input, therefore when you click generate and it updates root.user-input the LineEdit is still showing what it is holding internally instead of what's actually in root.user-input.

**Comment by ogoffart** [comment]
As @Vadolaa write, you indeed need a two way binding (`<=>`) for this.
