### ISSUE TITLE
Panic in slint compiler:  The remove return pass should have removed all return

### ISSUE THREAD

**Issue by npwoods** [slint-ui/slint#5430]
Steps to reproduce:
1. Open up attached minimal Rust project
2. `cargo build`
````
thread 'main' panicked at C:\<<redacted>>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\i-slint-compiler-.6.0\llr\lower_expression.rs:199:13:
  The remove return pass should have removed all return
`````
[bug-demo.zip](https://github.com/user-attachments/files/15893025/bug-demo.zip)

**Comment by ogoffart** [comment]
Thanks for the bug report.
I can reproduce it.

It needs two files to be reproduced:

treeview.slint:
```slint
export global MyFluentPalette {
    property <bool> dark-color-scheme: {
        return false;
    }
    out property <brush> control-foreground: dark-color-scheme ? #FFFFFF : #000000E6;
}
```

main.slint
```
import { MyFluentPalette } from "treeview.slint";
export component AppWindow inherits Window {
    out property <bool> foo: MyFluentPalette.dark-color-scheme ? true : false;
}```

Looks like property of global exported in another file are not properly handled

**Comment by ogoffart** [comment]
This happens for global on other files because then the property can be inlined, but it can also be reproduced by one file with a private property

```slint
export component AppWindow inherits Window {
    property <bool> xxx: {
        return false;
    }
    out property <string> foo: xxx ? "true" : "false";
}
```

The problem is that the condition contains a return:
`foo: if ({ return false; }) { "true" } else { "false" }`
Not only the returned is not removed, but it is wrong to inline returns

The remove return pass needs to be done before const propagation
