### ISSUE TITLE
Incorrect color theme on macOS after upgrading `winit`

### ISSUE THREAD

**Issue by Berrysoft** [slint-ui/slint#5705]
After `winit` upgrade from `0.30.2` to higher, the color theme on macOS is incorrect.

Note that `winit` seems to change the window color scheme series method since 0.30.3.

**Comment by tronical** [comment]
I can confirm that

**Comment by tronical** [comment]
It appears that this regressed with https://github.com/rust-windowing/winit/pull/3736, i.e. `Window::theme()` will only return a theme value previously set and `None` otherwise. This, however, is strictly speaking the way it is documented - so we might need platform specific code to obtain the system default.

**Comment by tronical** [comment]
[Winit 0.3.0.5](https://github.com/rust-windowing/winit/releases/tag/v0.30.5) fixes this. After a `cargo update` it works :)
