### ISSUE TITLE
`some-color.brighter(pct)` doesn't work on colors such as `red`

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#5753]
Reproducible on Windows 10 and https://slintpad.com/ with this code:

```slint
export component Demo {
    Rectangle {
        width: 70px;
        height: self.width;
        border-width: 5px;

        states [
            regular when !touch-area.has-hover : {
                border-color: gray;
                background: red;
            }

            hovered when touch-area.has-hover : {
                border-color: gray.brighter(80%);
                background: red.brighter(80%);

                // Works:
                //border-color: gray.darker(80%);
                //background: red.darker(80%);
            }
        ]

        touch-area := TouchArea {
        }
    }
}
```

The border gets brighter, but not the surface. `darker()` works on both, though.

**Comment by ogoffart** [comment]
Thanks for filling a bug.

`brighter doesn't work with some color such as `red`.
[Slintpad Example](https://slintpad.com/?snippet=export+component+Demo+%7B%0A++++VerticalLayout+%7B%0A++++++++r1+%3A%3D+Rectangle+%7B+background%3A+red%3B+%7D%0A++++++++Rectangle+%7B+background%3A+r1.background.brighter%2880%25%29%3B+%7D%0A++++%7D%0A%7D%0A)

`brighter` works by first converting to [HSV](https://en.wikipedia.org/wiki/HSL_and_HSV) and then increasing the value.
This is not clearly defined in our .slint documentation, but the Rust documentation for the Color type clearly defines this behavior.

The issue is that `red` is already maximum brightness in HSV (colors such as #f00 or #0f0 or #f0f or #fff or #000).

To proceed with this issue, we could either improve the docs saying this is the expected behavior, or change to a different algorithm for brightness that do not convert to HSV but rather increase the RGB component for example.

**Comment by Enyium** [comment]
> we could either improve the docs saying this is the expected behavior

That's strange. There's red, and there's bright red!

> or change to a different algorithm 

How about using [HSL instead of HSV](https://en.wikipedia.org/wiki/HSL_and_HSV)? In color pickers, I like HSL much better than HSV. The L slider goes from black over the H-and-S-defined color to white. I'm not sure how the percentages passed to `darker()` and `brighter()` would map to this slider, though. Should 100% map to the full or only half the L slider width?

**Comment by ogoffart** [comment]
The algoritm is actually based on CSS ans SASS and that's how it works.
For example this is an example using CSS: https://codepen.io/Nigel-Breslaw/pen/yLdXzaa

In light of that, we will not change this.

**Comment by Enyium** [comment]
Another name for HSV is HSB. So, `brighter()` fits with that. But there's still the possibility to add a `lighter()` function, based on the L in HSL. Wouldn't this be user-friendlier and make for more descriptive code than having to use `red.mix(white, 20%)`?
