### ISSUE TITLE
Every Alt+Tab to window moves focus

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#5823]
With Rust and Windows 10, every time I use Alt+Tab to activate the Slint window - not when using it to deactivate the window - the keyboard focus moves to the next element, as if I simply pressed Tab while the window stayed active.

**Comment by ogoffart** [comment]
Thanks for the bug report. I can also reproduce on X11 with winit.

**Comment by ogoffart** [comment]
The problem is the following:
The alt+tab event that focuses out of the window is not the problem because that one is intercepted.
But the alt+tab even that focus the window again causes the problem because the alt and tab keys are still pressed when the window gain focus. 
Then winit will send [synthetic events](https://docs.rs/winit/latest/winit/event/enum.WindowEvent.html#variant.KeyboardInput.field.is_synthetic) for all the keys currently pressed. They will even be in the order 1.tab, 2.alt.  So can't even detect the modifier keys.

**Comment by Enyium** [comment]
In the Ctrl+F search dialog of Windows Notepad, Ctrl+Tab works the same as Tab to change the control focus. There's also Shift+Tab, of course. Ctrl+Shift+Tab works the same as Shift+Tab there.

I know from other apps in the past that Ctrl+Tab may be used to be able to change the focus away from a multiline text box that supports intertion of tab characters with Tab.

Maybe it's a better strategy to check if both the down and up event were sent to the window, and if it's only the up event, reject it? When having the Slint window activated, it actually reacts on the Tab down event to change the focus, just like the search dialog in Notepad. So, it's strange to me that Slint reacts to the Tab up event after activating the window at all. I assume that the Tab down event isn't received.

Also, note that this bug depends on the speed of Alt+Tab. In normal speed, the bug happens. If you extend the time of holding Alt *alone* at the end of the key combo, the bug disappears.
