### ISSUE TITLE
Using tokio::time::sleep() in a future passed to spawn_local seems to hang

### ISSUE THREAD

**Issue by npwoods** [slint-ui/slint#5841]
In a future passed to `spawn_local`, I attempt to use `tokio::time::sleep` to wait for a short duration.  For some reason, it seems to `await` forever.

Steps to reproduce:
1. Unzip `bug-demo.zip` somewhere
2. `cargo run`
3. Click the button and observe the standard output
RESULT:  The `println!()` before the `sleep` is called but not the one afterwards
[bug-demo.zip](https://github.com/user-attachments/files/16604558/bug-demo.zip)

Interesting part of the code:
```
    app_window.on_clickme_clicked(move || {
        let fut = async move {
            println!("Button was clicked... about to sleep");
            sleep(Duration::from_millis(1000)).await;

            // PROBLEM:  for some reason we never end up here
            println!("Awoken from the sleep!");
        };
        spawn_local(fut).unwrap();
    });
````

**Comment by tronical** [comment]
The issue here is that your application uses the `current-thread` scheduler. Unfortunately that can't be used with Slint as we can't yield to it from the Slint event loop (unless you know of a way perhaps?).

You need to switch to the multi-threaded runtime to make it work:

```patch
diff --git a/Cargo.toml b/Cargo.toml
index 0543ce9..202f691 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -5,7 +5,7 @@ edition = "2021"

 [dependencies]
 slint = "1.7.1"
-tokio = { version = "1.38.0", features = ["rt", "time", "sync"] }
+tokio = { version = "1.38.0", features = ["rt", "time", "sync", "rt-multi-thread"] }

 [build-dependencies]
 slint-build = "1.7.1"
diff --git a/src/main.rs b/src/main.rs
index 6a3e60e..da514ec 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -5,7 +5,7 @@ use tokio::time::Duration;

 fn main() {
     // set up the tokio runtime
-    let tokio_runtime = tokio::runtime::Builder::new_current_thread()
+    let tokio_runtime = tokio::runtime::Builder::new_multi_thread()
         .enable_time()
         .build()
         .unwrap();
```

We recently updated our documentation to also reflect this: https://snapshots.slint.dev/master/docs/rust/slint/fn.spawn_local.html

This will also be part of the upcoming 1.7.2 release.
