### ISSUE TITLE
How to select only GL backend?

### ISSUE THREAD

**Issue by inferiorhumanorgans** [slint-ui/slint#587]
On MacOS:

```
$ cat Cargo.toml
[package]
name = "foo"
version = "0.1.0"
edition = "2021"

[dependencies]
sixtyfps = { version = "0.1.3", default-features = false, features = ["backend-gl"]}
```

(note: I had to blow away cargo's crates.io cache before cargo could even grok this even with resolve=2)

```
$ rm -rf target
$ cargo build >& /dev/null
$ otool -L target/debug/foo | grep -i qt
	/usr/local/opt/qt/lib/QtCore.framework/Versions/A/QtCore (compatibility version 6.0.0, current version 6.1.2)
	/usr/local/opt/qt/lib/QtGui.framework/Versions/A/QtGui (compatibility version 6.0.0, current version 6.1.2)
	/usr/local/opt/qt/lib/QtWidgets.framework/Versions/A/QtWidgets (compatibility version 6.0.0, current version 6.1.2)
```

I couldn't find anything in the documentation about choosing a backend so I took a wild guess with the features but as you can see Qt is still pulled in.

**Comment by ogoffart** [comment]
The problem is that sixtyfps-rendering-backend-default always end up enabling the qt backend :-(
I thin it is really hard to express this kind of optional but enabled by default dependence with cargo.

Anyway, the workaround for now is to define the `SIXTYFPS_NO_QT` env variable to `1`, then the build script of the qt backend will make it a dummy backend.
https://github.com/sixtyfpsui/sixtyfps/blob/master/docs/install_qt.md#how-to-disable-the-qt-backend

**Comment by ogoffart** [comment]
We've changed the way the features work so now if one use default-features = false and do not enable the Qt backend, it is not enabled
