### ISSUE TITLE
`debug()` adds undesired commas

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#5991]
Consider the following .slint code:

```slint
export component AppWindow inherits Window {
    property <int> value: 123;
    property <string> other-value: "abc";

    init => {
        debug("value:", root.value, "+++ other value:", root.other-value);
    }
}
```

It writes to the console:

```
value:, 123, +++ other value:, abc
```

On the other hand, when you run this JavaScript code:

```js
const value = 123;
const otherValue = "abc";
console.log("value:", value, "+++ other value:", otherValue);
```

...this is the output:

```
value: 123 +++ other value: abc
```

Following this precedent would mean Slint shouldn't output the commas.

**Comment by ogoffart** [comment]
the debug command is, as its name say, for debug purposes. The goal is to be as convenient as possible.
I thought the `,` may be helpul, but I might have been wrong. 
Note that you can already get the result without the coma if you yse `+` instead of coma.
```slint
debug("value:" + root.value + "+++ other value:" + root.other-value);
```
(but `+` only work with argument that can be converted to string, while debug otherwise support outputting the value of more types)


Note: the code that adds the coma is there:  (and can trivially be replaced by just a space)
https://github.com/slint-ui/slint/blob/80c497b3192c5b24abe49e454f4e1508106f55dc/internal/compiler/builtin_macros.rs#L313

**Comment by hunger** [comment]
I add `,` between parameters because that is how I separate items I pass into a function. And debug looks very much like a function to me.

But I have no strong feelings: I usually put in debugs for a few runs only and do not mind there being comas in the output (or not)... as long as the types get printed I am happy.

**Comment by Enyium** [comment]
I'd prefer `debug()` to behave more like the well-known `console.log()`. Since you're not against it, I'll do the trivial change.

> (but `+` only work with argument that can be converted to string, while debug otherwise support outputting the value of more types)

Exactly. I already read this in another issue regarding enums. So, it's again like `console.log()`: Printing something like `console.log("my DOM element:", $0);` gives you special output (in this case reactive output).
