### ISSUE TITLE
Select whole negative number on text input double click 

### ISSUE THREAD

**Issue by FloVanGH** [slint-ui/slint#6153]
If `input-type` is set to `number` and you double click on a negative number in a text input element, only the number itself is selected without the `-`. Expected behavior is, that also the  the `-` is part of the text selection.

originally reported at #6104

**Comment by tronical** [comment]
Intersting, this is kind of the opposite of commit 4b6b64f521554eae2eb11c595d4c9ee4d948e838 , where we don't want the default behaviour of click selection selecting at word boundaries. I think this needs to be handled on the spin box level again :-/

**Comment by ogoffart** [comment]
The question is whether this is even the expected behavior.
We can select the full thing with tripple click.
I've tried Qt as well as firefox showing this html `<input type="number" value="1" min="-999" max="999">` on linux and double click on the number doesn't select the minus sign.

I haven't tried other platform, but I don't think they'd be different.
So IMHO we can close this issue.

**Comment by tronical** [comment]
Fair point :) (no objection from me)
