### ISSUE TITLE
slint font rendering is very poor, how to solve it

### ISSUE THREAD

**Issue by xiacc-cn** [slint-ui/slint#6365]
See the picture below
![image](https://github.com/user-attachments/assets/3e4b362a-3110-485a-84fb-bbf625e34967)

**Comment by ogoffart** [comment]
Do you know what renderer/backend you are using? There are some differences between skia and femtovg. 
I think skia is used in the live preview, while femtovg is the default in a rust application unless you enable skia with a feature flag.

**Comment by nproux** [comment]
Not OP, but I ran into the same issue and changing to the skia renderer seems to resolve it for me. The font rasterization in the default renderer and default text family (for Windows environment at least) seems to be impressively bad right now. For reproduction I was using English characters at font sizes 20px and 24px, both bold and regular, with a Rust backend. Build and run in release mode and you should notice it right away. 

It might be a bug in the renderer rather than Slint itself, but I suggest that what Slint picks as the default renderer should probably be biased towards something that visually looks decent. New users aren't likely to dig into details of how to make things better if their initial testing has pretty poor results. That said your team might have other concerns I'm not aware of that make the current default choice the better tradeoff, so feel free to ignore me on that.

**Comment by mackrol** [comment]
Any progress on the font quality? Text layout and font rendering in the examples is extremely poor. Tested on Win10 1920x1200 100% text scaling 

1. uneven horizontal spacing between glyphs (see "consetetur"):

![image](https://github.com/user-attachments/assets/c226facf-9c86-4180-999a-e89b7db4c678)

or even worse

![image](https://github.com/user-attachments/assets/65b905c9-3601-492f-8d4d-9a2bf95adced)

2. incomplete glyphs (see "Item 1.3")

![image](https://github.com/user-attachments/assets/d2c6116f-3a52-4c72-9540-5271cabd08f6)

3. broken vertical placement of glyphs (see "0 Moves 15 Tiles left" message)

![image](https://github.com/user-attachments/assets/5f04d04b-141c-4ebd-9d21-4bb0b7653d58)

**Comment by hunger** [comment]
@mackrol: Did you try the skia renderer? It tends to render a bit nicer for me, but unfortunately is more error-prone to build, too :-/

**Comment by tronical** [comment]
This is a known issue, the quality of the built-in femtovg glyph rasterization using its own path renderer has seen frequent complaints. AFAICS everyone in the Rust ecosystem is using swash nowadays (bevy via cosmic-text, vello, etc.), and I'd like to move femtovg over to that, as well.

Meanwhile, I'll mark this as

Duplicate of #3742

**Comment by tronical** [comment]
Duplicate of #3742

**Comment by aa55-dev** [comment]
Is there a way to make it look better? This is what slint looks like compared to a Qt application.

<img width="701" height="150" alt="Image" src="https://github.com/user-attachments/assets/662a2bb5-abd3-4376-91d9-7e2695c4b4b1" />
