### ISSUE TITLE
SlintPad: Size not updated on property assignment

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6377]
Consider [this SlintPad demo](https://slintpad.com/?snippet=import+%7B+Button%2C+VerticalBox+%7D+from+%22std-widgets.slint%22%3B%0A%0Aexport+component+Demo+%7B%0A++++preferred-width%3A+0%3B%0A++++preferred-height%3A+0%3B%0A%0A++++property+%3Cstring%3E+prop%3A+%22a%22%3B%0A%0A++++VerticalBox+%7B%0A++++++++alignment%3A+start%3B%0A%0A++++++++Text+%7B%0A++++++++++++text%3A+root.prop%3B%0A++++++++%7D%0A%0A++++++++Button+%7B%0A++++++++++++text%3A+%22assign%22%3B%0A%0A++++++++++++clicked+%3D%3E+%7B%0A++++++++++++++++root.prop+%3D+%22abcdefghijklmnopqrstuvwxzy0123456789%22%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native):

```slint
import { Button, VerticalBox } from "std-widgets.slint";

export component Demo {
    preferred-width: 0;
    preferred-height: 0;

    property <string> prop: "a";

    VerticalBox {
        alignment: start;

        Text {
            text: root.prop;
        }

        Button {
            text: "assign";

            clicked => {
                root.prop = "abcdefghijklmnopqrstuvwxzy0123456789";
            }
        }
    }
}
```

- It starts very small.
- When clicking the button, it's size doesn't change, although it should. (The same Slint code in a Windows 10 project behaves correctly.)
- When then trying to *de*crease the size using the resize handles, the size jumps to the larger size it should previously have been extended to when the property was assigned.

**Comment by hunger** [comment]
Yes, that happens.

The problem is that there is no way to know when something changed size or position. So there is not reliable way to update the selection rectangle :-/

**Comment by tronical** [comment]
`Demo`'s `minimum-width` changes. Is that not detectable?

In the snippet it works for me on the layout: 

```slint
   VerticalBox {
        changed min-width => {
            debug("new min-width \{self.min-width/1px}");
        }
...
```

We do have an implementation of the layout_info for the component container, don't we? So maybe what's the previewed component here (`Demo`) can be observed?

**Comment by hunger** [comment]
I am interested in changes to the size of the selected element, not the window. In this case one will change the other, but that is not true in general.

**Comment by tronical** [comment]
Since you're retrieving the size and position via the interpreter's API (`element_positions`, etc.), maybe in case you want to track changes, use a `PropertyTracker`? Or if you expose a call to such functions directly in Slint, then storing that in a property in Slint should update automatically (and work with `changed XXX =>`).

**Comment by ogoffart** [comment]
> I am interested in changes to the size of the selected element, not the window. In this case one will change the other, but that is not true in general.

I think the problem here is not the selected element, it is the constraint of the Window not being respected.

Eg, after clicking the button in the slintpad link from the description, i see this: 
![image](https://github.com/user-attachments/assets/934c0f15-2f94-485d-bec3-04e22e096d97)
but the text is bigger than that and so is the minimum size, and trying to resize the component shows that.

> The problem is that there is no way to know when something changed size or position. 

There are ways. Especially now with changed callback.
In native code there is PropertyTracker.

> So there is not reliable way to update the selection rectangle :-/

Yes there are ways, but this is anyway not what this issue is about.

**Comment by hunger** [comment]
True, seems like I misunderstood the issue :-/ It's much simpler to fix the real issue then the one I was thinking we had here.
