### ISSUE TITLE
Allowing parameter names in callback declarations

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6527]
Currently, you have to specify parameter names in callbacks as comments:

```slint
callback move-list-item(/*up:*/ bool);
```

This isn't satisfying. #5859 created an experimental feature that allows you to write:

```slint
callback move-list-item(up: bool);
```

However, @ogoffart wrote in the PR:

> I rather keep that experimental.

Please make this a regular feature!

What's missing is just that the parameter name is also shown in VS Code when you hover over the callback's name at a call site. Currently, even when using `SLINT_ENABLE_EXPERIMENTAL_FEATURES=1`, VS Code just shows the help overlay `callback move-list-item(bool)`. It would be very useful if it showed `callback move-list-item(up: bool)`.

**Comment by hunger** [comment]
I added labels based on improving the VSCode help overlay only;-)

**Comment by ogoffart** [comment]
What we can do in the LSP with these names:

  - [ ] Show them in the tooltip (hover)
  - [ ] pre-complete their name when auto-completing a callback.  (eg, complete to `foobar(name1, name2) => {$1}` instead of `foobar => {$1}` currently
  - [ ] implements the `textDocument/signatureHelp` request (also for function)

Anyway, before stabilization, we also need to consider whether it is compatible with all the change we could want to do in the future, like named argument calling and stuff.

Also need to be done
 - [ ] Give name to the arguments in the builtin callbacks
 - [ ] Give names to the argument in the widget style (and make sure they are consistant accross styles)

Some ideas:
 - [ ] Give a warning when the name of an argument in a callback is the same as another argument in another position.
