### ISSUE TITLE
`CheckBox` has more padding on the sides than other components...

### ISSUE THREAD

**Issue by alexeyabel** [slint-ui/slint#6596]
...as can be seen on the screenshot with approximate pixel margins.
![Screenshot_20241020_175441-slint](https://github.com/user-attachments/assets/9dde6be6-aeaa-435b-a662-0f2b84d7955a)

The components are inside a `HorizontalBox` but since the margins are different, it must be due to the `CheckBox` AFAICS. Because of this additional space, combinations of components as seen in the image look off. I tried `padding-right:0;` but it had no visible effect.

It would be nice to
1. have an option to disable all margins on the `CheckBox` so that only spacing of the parent component is applied
2. (maybe) the space between the checkbox and its text (currently ~12 px) be 8px. Not sure if 8px instead of 12px make it look too cramped.

Here is a picture of how this would look like with ~8px inbetween.
![Screenshot_20241020_175441-slint-8px](https://github.com/user-attachments/assets/a26f3f2d-ebdf-4a9b-9a16-0361849891d2)

**Comment by Enyium** [comment]
The same problem exists vertically (separator line between widgets; no layout padding and spacing; [SlintPad](https://slintpad.com/?snippet=import+%7B+Button%2C+VerticalBox%2C+CheckBox+%7D+from+%22std-widgets.slint%22%3B%0A%0Acomponent+Seperator+%7B%0A++++Rectangle+%7B%0A++++++++background%3A+black%3B%0A++++++++height%3A+1phx%3B%0A++++%7D%0A%7D%0A%0Aexport+component+Demo+%7B%0A++++VerticalLayout+%7B%0A++++++++alignment%3A+start%3B%0A%0A++++++++Seperator+%7B%7D%0A++++++++CheckBox+%7B%0A++++++++++++text%3A+%22Foo%22%3B%0A++++++++%7D%0A++++++++Seperator+%7B%7D%0A++++++++CheckBox+%7B%0A++++++++++++text%3A+%22Foo%5Cnbar%22%3B%0A++++++++%7D%0A++++++++Seperator+%7B%7D%0A++++++++Text+%7B%0A++++++++++++text%3A+%22Foo%5Cnbar%22%3B%0A++++++++%7D%0A++++++++Seperator+%7B%7D%0A++++++++Button+%7B%0A++++++++++++text%3A+%22Foo%22%3B%0A++++++++%7D%0A++++++++Seperator+%7B%7D%0A++++%7D%0A%7D%0A&style=fluent-light)):

![checkbox-padding-problems](https://github.com/user-attachments/assets/0514401b-c3de-409e-8680-36f32c321378)

This leads to an inconsistent look in my app where I have check boxes with one-line and with two-line text.

Isn't spacing the responsibility of layouts? But the box itself is surrounded by space additional to what a layout adds. This also creates an indent on the left. But on Windows, the check boxes in the Notepad search dialog and the Directory Opus preferences dialog don't have indents.

**Comment by Enyium** [comment]
> have you checked it on master?

Yes. The indents to the left of check boxes are gone (so, what I see includes your changes), but the large gap between one-line check boxes as well as the uneven gap for one-line and two-line check boxes next to separator lines are still there.

Your PR only removes the horizontal properties `padding-left` and `padding-right`, nothing vertical.

**Comment by szecket** [comment]
it appears the distance for 2 line and 1 line checkboxes is the same _for the box_ but doesn't create extra space for the text.   This is an observation based on the visual appearance, not based on looking at any code...

**Comment by Enyium** [comment]
Thanks, I can't see any vertical problems anymore.

But are you sure the gap between box and text isn't too large? It's smaller in other apps I checked, like Firefox (settings), or Directory Opus (Qt-based, I think).

My app uses normal check boxes as well as check boxes with buttons instead of text, and the normal check boxes have a larger gap, which also seems too large. See [this SlintPad demo](https://slintpad.com/?snippet=import+%7B+VerticalBox%2C+CheckBox%2C+Button+%7D+from+%22std-widgets.slint%22%3B%0A%0Aexport+component+Demo+%7B%0A++++VerticalBox+%7B%0A++++++++alignment%3A+start%3B%0A%0A++++++++CheckBox+%7B%0A++++++++++++text%3A+%22Do+something%22%3B%0A++++++++%7D%0A%0A++++++++HorizontalLayout+%7B%0A++++++++++++alignment%3A+start%3B%0A%0A++++++++++++CheckBox+%7B%7D%0A++++++++++++Button+%7B%0A++++++++++++++++text%3A+%22Do+something%22%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=fluent-light) (again, checked with master, of course):

![button-check-box](https://github.com/user-attachments/assets/770192c9-f0cf-4c91-96e2-aa26d6789b6c)

> it appears the distance for 2 line and 1 line checkboxes is the same _for the box_ but doesn't create extra space for the text.

I'm not sure a check box should add *any* free space towards other widgets. And with these recent changes, it doesn't.
