### ISSUE TITLE
VoiceOver navigation cause panic

### ISSUE THREAD

**Issue by DataTriny** [slint-ui/slint#6922]
### Bug Description

On MacOS, sometimes when using VoiceOver commands to navigate, the application crashes with this error:

```
thread 'main' panicked at internal/backends/winit/winitwindowadapter.rs:1051:32:
already borrowed: BorrowMutError
```

This panic only occurs when landing on certain type of widgets, I haven't been able to find which ones yet.

### Steps to reproduce

- Enable VoiceOver
- Start the 7GUIs/CRUD example
- Use Control+Option+Right arrow to explore the UI, use it twice to land on the list view

### Environment Details

- Slint Version: commit c6839a77a6351e4a80a5f14d13c6a34526300769
- Platform/OS: MacOS 11.7.10
- Programming Language: N/A
- Backend/Renderer: winit

### Product Impact

I am using the CRUD example as a testing ground for adding listbox support to AccessKit. I can't make progress on MacOS due to this bug.

**Comment by tronical** [comment]
Interesting. I thought that perhaps this is a regression of ea6e5b284143fde413b8cee3b62b11b69a03471c, but the `borrow_mut()` was there before as well.

**Comment by tronical** [comment]
AFAICS this happens when the accessibility sub-system issues a `Action::Focus` request on a node. Processing that results in a focus change, which triggers this:

```rust
    pub fn handle_focus_item_change(&mut self) {
        self.inner.update_if_active(|| TreeUpdate {
            nodes: vec![],
            tree: None,
            focus: self.nodes.focus_node(&self.window_adapter_weak),
        })
    }
```

Sadly, `update_if_active()` requires `&mut self`. I wish access kit would use interior mutability for more fine-grained control, instead of delegating this to the app / framework.

I'll try to see if I can work around it though.

**Comment by tronical** [comment]
Thank you for the excellent bug report :)
