### ISSUE TITLE
use log::debug macro for debug function in .60 language

### ISSUE THREAD

**Issue by Be-ing** [slint-ui/slint#865]
It would be nice if using the built-in debug function in .60 files autogenerated Rust code which used the debug macro from the [log](https://lib.rs/crates/log) crate. This would allow applications to choose the logging implementation instead of always printing directly to standard out. It would also be nice to add functions for the other log levels (trace, info, warn, error).

**Comment by ogoffart** [comment]
Yeah, it somehow should be configurable what the 'debug' does. 
The log crate is great because it is already configurable, but It does nothing by default if I understand correctly, which is not ideal because I don't want to have the user to set it up for debug to work in the default case.

I wonder how to configure it. A feature of the sixtyfps crate maybe?

**Comment by tronical** [comment]
I agree, log is create but the lack of a default logger may be a surprise. It would be nice if this was opt-in. Maybe this brings us back to #267 and therefore a place where to also configure aspects of the compiler output?

**Comment by Be-ing** [comment]
#267 could be one way to handle this. Alternatively there could be a Cargo feature to toggle using a default logger (I suggest [pretty_env_logger](https://lib.rs/pretty_env_logger)) which could be disabled if an application wants to use something different. The project configuration file might be more straightforward for application developers who are not using Rust.

**Comment by Be-ing** [comment]
The log crate is designed so that libraries aren't expected to initialize a logging implementation. I think Rust developers might be surprised if SixtyFPS initialized a default logger. Perhaps a logger could be initialized automatically when using a language other than Rust?

**Comment by ogoffart** [comment]
I don't think #267 is the right place, because that's a runtime feature more than a compiler feature. 
The compiler would generate a call to `sixtyfps::internal::debug(...)`   instead of to `println!`  as it currently does.
Then the implementation of `fn sixtyfps::internal::debug` can simply call to `log::debug` if the `log` feature is enabled on the `sixtyfps` crate,  or `println` otherwise.

I think that's the simpler to do, rather to have the compiler generate call to `log::debug` directly forcing this to be in scope for the generated code.

**Comment by tronical** [comment]
On the other hand, if the compiler were to emit `log::debug`, then the user/developer want wants to filter log output of their `.60` code using the `env_logger` shouldn't have to enable logging in `sixtyfps::internal::debug`. I think it would be great if they could just write `RUST_LOG=ui/blah.60`.

If the compiler was configurable to emit `debug!(target: "ui/blah.60", "...");` for `debug()` calls in `ui/blah.60` this would be a natural integration into the log crate IMO.

**Comment by Be-ing** [comment]
It would be really nice if the compiler generated targets for the log macros based on the element name and have them under a global namespace for all generated elements, for example `RUST_LOG=sixtyfps_generated::UserDefinedElement=debug`.

**Comment by Be-ing** [comment]
If SixtyFPS initialized a logger by default, I think that might cause trouble when a Rust application also initializes a logger. So I suggest to not initialize a logger for Rust applications but do initialize one for other languages because the applications don't have the opportunity to do that on their own.

**Comment by ogoffart** [comment]
I think the source code location can easily be fixed with `#[track_caller]`.
But if it can't, yeah, that'd be an argument in favor of keeping it a macro.  Yet, the `sixtyfps::internal::debug!` macro could still redirect to either println or the log macro.
But that still be the location of the generated code and not the location of the debug statement in .60.

That said, the compiler could generate code to `sixtyfps::internal::debug(expression_to_print, "foo.60", 82, "MyComponent", "property_foo")`  and then these arguments can be passed to the log crate.

**Comment by tronical** [comment]
> That said, the compiler could generate code to sixtyfps::internal::debug(expression_to_print, "foo.60", 82, "MyComponent", "property_foo") and then these arguments can be passed to the log crate.

That's a good point :)

**Comment by Be-ing** [comment]
Using `println` directly in the generated code would mean that C++ and JS application developers wouldn't be able to take advantage of the log filtering capabilities possible with Rust.

**Comment by ogoffart** [comment]
I tagged this as a "good firs issue" because it is fairly easy to implement.
1. Add a runtime `sixtyfps::internal::debug` function in sixtyfps-rs/lib.rs that calls println!
2. Change the code generation in rust.rs 
https://github.com/sixtyfpsui/sixtyfps/blob/master/sixtyfps_compiler/generator/rust.rs#L1726   (if we want to add the source code location and things that'd be a bit trickier though, the information would need to be added as an extra llr::Expression::Struct argument to the function)
3. Add a feature `log` and modify sixtyfps::internal::debug accordingly.
