### ISSUE TITLE
sixtyfps-fmt formats to invalid syntax

### ISSUE THREAD

**Issue by Zajozor** [slint-ui/slint#898]
Kind of a followup from https://github.com/sixtyfpsui/sixtyfps/discussions/895#discussioncomment-2070964

I noticed that the formatter is pretty mvp and gives sometimes incorrect behaviour, see example gif below.

![CleanShot 2022-01-29 at 15 32 43](https://user-images.githubusercontent.com/1835434/151663040-2dd752cd-6e08-45c0-b26f-b5d44804d37a.gif)

Would you mind me looking into this? The formatter tool seems to be a relatively small project, so it should not be much of a trouble.

-- side question 1
Is it a conscious decision to put no space after the component name and before { ? (see below) If not, can we change it to put space there?
![CleanShot 2022-01-29 at 15 23 33@2x](https://user-images.githubusercontent.com/1835434/151662910-a7ebc6ee-0163-4760-b527-a3c078ab5261.png)

-- side question 2
I guess in general I'd like to know if you are willing to review/accept some PRs related to the formatter..
Maybe it could get a README, tests, vscode extension, config, ...

Thanks! :)

**Comment by ogoffart** [comment]
> Would you mind me looking into this? The formatter tool seems to be a relatively small project, so it should not be much of a trouble.

That would be great!

> Is it a conscious decision to put no space after the component name and before { ? (see below) If not, can we change it to put space there?

This is not a conscious decision, no.
The current state is more like a proof-of-concept prototype. 
If anything, i think we would want to have something which is close to what we do in the examples.

Looking into this particular case, it seems like the comment there is no longer accurate, and it should be `" "` instead of `""` line 192

https://github.com/sixtyfpsui/sixtyfps/blob/e2676a5b00d76b16beea1c1457e3c1ce9e50545f/tools/fmt/fmt.rs#L191-L192

> I guess in general I'd like to know if you are willing to review/accept some PRs related to the formatter..

Of course, that would be awsome to see you contributing.

> Maybe it could get a README, tests, vscode extension, config, ...

yes, so much things :-)
